### PR TITLE
d2m: broadcast non tiled dim

### LINKED ISSUE #7064: Tiled multiply with different shard sizes not supported
### Error signature
```
loc(...): error: 'd2m.generic' op shard shape mismatch between operand[0] and operand[1]
```

### Affected

2 component(s) affected in model **gpt_oss_120b_shlo.mlir.ttir.mlir_ttir_decomposition.ttir**.

---

### Fails at

Line 306, op `ttir.multiply` in pass **ttir-to-d2m**

```mlir
    %300 = "ttir.multiply"(%193, %206) : (tensor<1x16x1x32xbf16>, tensor<1x1x1x32xbf16>) -> tensor<1x16x1x32xbf16>
    %301 = "ttir.multiply"(%194, %206) : (tensor<1x16x1x32xbf16>, tensor<1x1x1x32xbf16>) -> tensor<1x16x1x32xbf16>
    %302 = "ttir.multiply"(%195, %206) : (tensor<1x2x1x32xbf16>, tensor<1x1x1x32xbf16>) -> tensor<1x2x1x32xbf16>
    %303 = "ttir.multiply"(%196, %206) : (tensor<1x2x1x32xbf16>, tensor<1x1x1x32xbf16>) -> tensor<1x2x1x32xbf16>
    %304 = "ttir.multiply"(%101, %207) : (tensor<1x16x1x32xbf16>, tensor<1x1x1x32xbf16>) -> tensor<1x16x1x32xbf16>
    %305 = "ttir.multiply"(%100, %207) : (tensor<1x16x1x32xbf16>, tensor<1x1x1x32xbf16>) -> tensor<1x16x1x32xbf16>
    %306 = "ttir.multiply"(%104, %207) : (tensor<1x2x1x32xbf16>, tensor<1x1x1x32xbf16>) -> tensor<1x2x1x32xbf16>
```
---
```

### PR DESCRIPTION
**Pull request by anuragsingh-tt**
### Ticket
Resolves #7064 

### Problem description
isImplicitBcast was true only if tileBcastTypes had row/col/scalar broadcast. That only captures broadcast in tile-local dims, not broadcast on earlier tensor dims.

Also added builder test.

### CODE REVIEW

File: lib/Conversion/TTIRToD2M/TTIRToD2M.cpp [hunk 1]
```diff
@@ -765,9 +765,15 @@ class D2MNamedElementwiseRewriter final
...
-    const bool isImplicitBcast = llvm::any_of(tileBcastTypes, [](auto type) {
+    const bool hasTileBcast = llvm::any_of(tileBcastTypes, [](auto type) {
       return type != d2m::TileBcastType::None;
     });
+    const bool hasBroadcastIndexingMap =
+        !bcastIndexingMaps.empty() &&
+        llvm::any_of(ArrayRef<mlir::AffineMap>(bcastIndexingMaps)
+                         .take_front(origInputs.size()),
+                     [](mlir::AffineMap map) { return !map.isIdentity(); });
+    const bool isImplicitBcast = hasTileBcast || hasBroadcastIndexingMap;
```
Comment (wenbinlyuTT) [inline lib/Conversion/TTIRToD2M/TTIRToD2M.cpp]: I think if tile-level bcast is detected, then at least one of the inner dim should be mapped to the const expr of 0? This `||` here might be reduandant.

File: test/python/golden/ttir_ops/eltwise/test_ttir_binary.py [hunk 2]
```diff
@@ -211,6 +211,48 @@ def binary_op_fn(in0: Operand, in1: Operand, builder: TTIRBuilder) -> Operand:
...
+    ids=shapes_list_str,
+)
+@pytest.mark.parametrize("dtype", [torch.float32], ids=["f32"])
+@pytest.mark.parametrize("target", ["ttmetal"])
+@pytest.mark.parametrize(
+    "test_fn",
+    [add, subtract, multiply],
+    ids=["add", "subtract", "multiply"],
+)
+def test_binary_ops_broadcast_shard_dims(
```
Comment (wenbinlyuTT) [inline test/python/golden/ttir_ops/eltwise/test_ttir_binary.py]: I think this test should be moved to near the existing `test_implicit_bcast_inner_2D` test.
Also, we should add more tests: 3/4/5-D, and larger tensors that exceed one tile per shard even on BH.

File: lib/Conversion/TTIRToD2M/TTIRToD2M.cpp (hunk 1 above)
Comment (anuragsingh-tt) [reply lib/Conversion/TTIRToD2M/TTIRToD2M.cpp]: Yes, `hasTileBcast` is a subset of `hasBroadcastIndexingMap`. I didn't touch the existing check but I can just remove it.

File: test/python/golden/ttir_ops/eltwise/test_ttir_binary.py (hunk 2 above)
Comment (anuragsingh-tt) [reply test/python/golden/ttir_ops/eltwise/test_ttir_binary.py]: Done.
