### PR TITLE
Fix context mismatch when comparing MLIR objects

### LINKED ISSUE #2813: Fixed context in static initialized object causing issues
In [this line](https://github.com/tenstorrent/tt-mlir/blob/16deada9008288e64731b28bf2ee67e603b2fec4/include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h#L965), the `nulloptAttr` object is created with the current context. This is problematic because if, sometime down the line, someone calls the `operator|` with `lhs` from a different (new) context, even if the `lhs` object is a `nullptr` object, it will be `!=` to `nulloptAttr` because their contexts differ. The end result will be that `lhs` will be returned instead of `rhs`.

This issue was encountered when running multiple pipelines from tt-forge-fe.

### PR DESCRIPTION
**Pull request by svuckovicTT**
### Ticket
#2813 

### Problem description
Details in linked ticket.

### What's changed
Fixed by removing `static` keyword.

### Checklist
- [ ] New/Existing tests provide coverage for changes

Closes #2813

### CODE REVIEW

File: include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h [hunk 1]
```diff
@@ -962,7 +962,7 @@ class EmitCTTNNEmitter {
 // For example, instead of calling `emit<std::variant<int32_t, float>>(attr)`,
 // one can call `emit<int32_t>(attr) | emit<float>(attr)`.
 inline mlir::Attribute operator|(mlir::Attribute lhs, mlir::Attribute rhs) {
-  static const mlir::Attribute nulloptAttr = emitc::OpaqueAttr::get(
+  const mlir::Attribute nulloptAttr = emitc::OpaqueAttr::get(
```
Comment (azecevicTT) [inline include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h:965]: Remove const as well.

**Review by azecevicTT — APPROVED** [review]

File: include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h (hunk 1 above)
Comment (svuckovicTT) [reply include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h:965]: Curious - why?

Comment (azecevicTT) [reply include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h:965]: TBH I'm not sure why did I put it in the first place, I don't see much value in const here, because `Attribute`s are immutable by design.

Comment (svuckovicTT) [reply include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h:965]: I think it's good to have it there as it signifies intent - I'm inclined to leave it as-is unless you have a strong opinion?
