### PR TITLE
multi tile fix

### LINKED ISSUE #5080: [D2M] Add support for multi-tile indexing into dest register
### Describe the bug

Currently all intermediate loads and stores in fused chains don't factor in loops used for multi tile indexing and assumed to use 0,0 indexing.

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by dlokeTT**
### Ticket
Closes #5080 

### Problem description
Assumed that we were only indexing 0, 0 for the tile so it would fail in multi tile situations.

### What's changed
Use the loop variables to get which tile we should be indexing in multi tile situations.

### Checklist
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: lib/Dialect/TTIR/Transforms/InsertDstRegisterAccess.cpp [hunk 1]
```diff
@@ -299,7 +303,19 @@ struct TTIRInsertDstRegisterAccessRewriter final
...
-          dstRegisterAllocation[op] = allocatedIndex;
+
+          // Collect induction variables from containing loops
+          SmallVector<Value> loopInductionVars;
+          for (Operation *ancestor = op->getParentOp(); ancestor != nullptr;
+               ancestor = ancestor->getParentOp()) {
+            if (auto affineFor = dyn_cast<affine::AffineForOp>(ancestor)) {
+              loopInductionVars.push_back(affineFor.getBody()->getArgument(0));
+            }
+          }
```
Comment (nsmithtt) [inline lib/Dialect/TTIR/Transforms/InsertDstRegisterAccess.cpp]: I think technically we need to use `getNonParticipatingLoopDims` and skip the loop dims that this set returns.  This'll be a requirement for matmul fusion I believe.  That said, I don't have concrete IR to base this on, so I think it'll just fail because the number of loopInductionVars here will exceed the rank of the memref that's being loaded/stored to.

**Review by nsmithtt — APPROVED** [review]

File: lib/Dialect/TTIR/Transforms/InsertDstRegisterAccess.cpp (hunk 1 above)
Comment (dlokeTT) [reply lib/Dialect/TTIR/Transforms/InsertDstRegisterAccess.cpp]: Hmm yea that makes sense. Should I include a check in this pr or just be on the lookout for when we get to matmul fusion?

Comment (nsmithtt) [reply lib/Dialect/TTIR/Transforms/InsertDstRegisterAccess.cpp]: Maybe it's better to add an assert for now, below where we plug this into the load/store op, we can check that the resulting indices match the rank of the memref.  We could add some comment in the assert or link it to this thread in the message.

**Review by xanderchin — APPROVED** [review]

**Comment by jojo-771771** [comment]
I can work on this. Please assign!

**Comment by jojo-771771** [comment]
I can work on this. Please assign!

**Comment by jojo-771771** [comment]
I can work on this. Please assign!
