### PR TITLE
Fix clang-tidy errors, closes #189

### LINKED ISSUE #189: Fix lint errors with runtime build
## Fix lint error with ttnn::Tensor tilize and ttnn::to_layout

```
/opt/ttmlir-toolchain//venv/bin/clang-tidy -p=build /localdev/vmilosevic/tt-mlir/runtime/lib/ttnn/program.cpp
/localdev/vmilosevic/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/decorators.hpp:224:13: error: static assertion failed due to requirement 'detail::has_execute_on_worker_thread() ^ detail::has_execute_on_main_thread()': Operation must either implement execute_on_worker_thread or execute_on_main_thread. [clang-diagnostic-error]
  224 |             detail::has_execute_on_worker_thread<concrete_operation_t, args_t&&...>() xor
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  225 |                 detail::has_execute_on_main_thread<concrete_operation_t, args_t&&...>(),
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/localdev/vmilosevic/tt-mlir/runtime/lib/ttnn/program.cpp:21:25: note: in instantiation of function template specialization 'ttnn::decorators::operation_t<0, ttnn::operations::core::ToLayout>::operator()<tt::tt_metal::Tensor &, const tt::tt_metal::Layout &, const std::nullopt_t &, const std::nullopt_t &, std::nullptr_t>' requested here
   21 |   return ttnn::to_layout(unsqueezeTensor, ttnn::TILE_LAYOUT, std::nullopt,
      |                         ^
/localdev/vmilosevic/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/decorators.hpp:224:87: note: expression evaluates to 'false ^ false'
  224 |             detail::has_execute_on_worker_thread<concrete_operation_t, args_t&&...>() xor
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
  225 |                 detail::has_execute_on_main_thread<concrete_operation_t, args_t&&...>(),
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/localdev/vmilosevic/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/decorators.hpp:283:49: error: no member named 'execute_on_main_thread' in 'ttnn::operations::core::ToLayout' [clang-diagnostic-error]
  283 |             auto output = concrete_operation_t::execute_on_main_thread(std::forward<decltype(args)>(args)...);
      |                                                 ^
21157 warnings and 2 errors generated.
```

## Steps to reproduce

```
> cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DTTMLIR_ENABLE_RUNTIME=ON -DTTMLIR_ENABLE_RUNTIME_TESTS=ON
> cmake --build build --config Release
> cmake --build build -- clang-tidy
```

## After fix
After fixing this locally re-enable linting with runtime build.
Remove line:

```if: matrix.enable_runtime == 'OFF'``

in .github/workflows/build.yml

### PR DESCRIPTION
**Pull request by nsmithtt**

### CODE REVIEW

File: runtime/lib/ttnn/program.cpp [hunk 1]
```diff
@@ -94,21 +98,19 @@ updateLayoutAndDataType(const ::ttnn::Tensor &inputTensor,
...
+// tile shape, blocked by issue
 static void
 run(::tt::target::ttnn::ToMemoryConfigOp const *op, ::ttnn::Device &device,
     std::unordered_map<std::uint32_t, ::ttnn::Tensor *> &liveTensors,
     std::list<::ttnn::Tensor> &tensorPool) {
   const ::ttnn::Tensor &inputTensor = *liveTensors.at(op->in0()->global_id());
-  TT_FATAL(isOnHost(inputTensor) or isOnDevice(inputTensor),
-           "Unsupported storage type {}", inputTensor.storage_type());
+  assert((isOnHost(inputTensor) or isOnDevice(inputTensor)) &&
+         "Unsupported storage type");
```
Comment (nsmithtt) [inline runtime/lib/ttnn/program.cpp:109]: @jnie-TT, unfortunately we cannot use `TT_FATAL`, we just happened to pull in metal's `assert.hpp`, but this is not public API.

File: lib/Dialect/TT/IR/TTOpsTypes.cpp [hunk 2]
```diff
@@ -131,11 +131,10 @@ mlir::tt::SystemDescAttr::getFromPath(MLIRContext *context, std::string &path) {
 
   // Acquire chip descs
   std::vector<tt::ChipDescAttr> chip_desc_list;
-  for (auto element : *binary_chip_desc) {
-
+  for (auto const *element : *binary_chip_desc) {
```
Comment (nsmithtt) [inline lib/Dialect/TT/IR/TTOpsTypes.cpp:134]: clang-tidy suggests all uses of `auto` are at least qualified with specifiers.

File: runtime/lib/ttnn/program.cpp (hunk 1 above)
Comment (jnie-TT) [reply runtime/lib/ttnn/program.cpp:109]: Sounds good... Thanks for updating this!

**Review by jnie-TT — APPROVED** [review]

**Review by nobradovictt — APPROVED** [review]

**Review by sdjordjevicTT — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]
