### PR TITLE
[TTNN Dialect] Fix ops which don't support dps

### LINKED ISSUE #844: Remove dps operand on ttnn operations which don't support dps

### PR DESCRIPTION
**Pull request by mtopalovicTT**
Minor: Remove dps op from all ttnn ops which don't support dps.

closes #844

### CODE REVIEW

File: lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp [hunk 1]
```diff
@@ -49,6 +49,16 @@ static Value getOrInsertDevice(ConversionPatternRewriter &rewriter,
   return deviceOp.getResult();
 }
 
+template <typename OpAdaptor>
+static void removeDpsOp(ConversionPatternRewriter &rewriter,
```
Comment (svuckovicTT) [inline lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp:53]: Rename to `removeDestination` or `undoDps` or something like that.

**Review by svuckovicTT — APPROVED** [review]
Tagging @tapspatel, @jnie-TT to check ttrt changes.

**Review by sdjordjevicTT — APPROVED** [review]

File: lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp [hunk 2]
```diff
@@ -296,9 +302,10 @@ class SoftmaxOpConversionPattern : public OpConversionPattern<ttir::SoftmaxOp> {
   LogicalResult
   matchAndRewrite(ttir::SoftmaxOp op, OpAdaptor adaptor,
                   ConversionPatternRewriter &rewriter) const override {
+    removeDpsOp(rewriter, adaptor);
```
Comment (sdjordjevicTT) [inline lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp:305]: Not necessarily in this change(maybe we can create an issue now), but can we add a paragraph in the doc describing "how to add op" something about DPS vs non-DPS op, and how to handle them in TTNN conversion?

File: test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir [hunk 3]
```diff
@@ -2,7 +2,6 @@
 #any_device = #tt.operand_constraint<dram|l1|scalar|tile|any_device|any_device_tile>
 module attributes {} {
   func.func @forward(%arg0: tensor<32xf32>, %arg1: tensor<512x128xf32>) -> tensor<32x128xf32> {
-    // CHECK: %[[C:.*]] = "ttnn.empty"[[C:.*]]
     %0 = tensor.empty() : tensor<32x128xf32>
     // CHECK: %[[C:.*]] = "ttnn.embedding"[[C:.*]]
```
[the remark this answers is not in the document]
Comment (mtopalovicTT) [reply test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir:6]: If you mean something like this?
`// CHECK: %0 =  "ttnn.embedding" [[C:.*]]`

I don't think we can do that since there can be meny ops preceding ttnn.embedding

[the remark this answers is not in the document]
Comment (sdjordjevicTT) [reply test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir:6]: In this specific example, I meant to verify that there is no empty op in the ttnn IR...

[the remark this answers is not in the document]
Comment (svuckovicTT) [reply test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir:6]: Short google shows `CHECK-NOT` directive as an option, could we try that?

[the remark this answers is not in the document]
Comment (mtopalovicTT) [reply test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir:6]: we can

File: lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp (hunk 1 above)
Comment (nsmithtt) [reply lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp:53]: Nit: this name kinda sounds like it's removing the op itself.  Maybe `removeDpsEmptyOp`.  Also are we just missing some traits that would auto-cleanup the empty's?  It seems like it might be unnecessary to manually erase them.

Comment (mtopalovicTT) [reply lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp:53]: Didn't know about this trait. Added tnx nick

File: lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp (hunk 2 above)
Comment (mtopalovicTT) [reply lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp]: Added #872

Comment (sdjordjevicTT) [reply lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp]: Please associate issue with MLIR Dialect\Passes component, so we don't miss it :)

**Review by nsmithtt — APPROVED** [review]
