### PR TITLE
[Shardy] Bugfix for SliceOp start indices

### LINKED ISSUE #6425: [Shardy] Slice op inferred shape incompatible with the expected shape
`UpdateGlobalToLocalShape` pass converts slice op with incorrect start limits. 

Graph to reproduce the error with `stablehlo-pipeline`.
```
sdy.mesh @mesh = <["model"=1, "batch"=2]>
func.func @main(%arg0: tensor<2560x9728xbf16> {mhlo.frontend_attributes = {xla.sdy.sharding = "#sdy.sharding<@mesh, [{}, {\22batch\22}]>"}, mhlo.sharding = "{devices=[1,2]<=[2]}", ttcore.argument_type = #ttcore.argument_type<parameter>}, %arg1: tensor<19456x2560xbf16> {mhlo.frontend_attributes = {xla.sdy.sharding = "#sdy.sharding<@mesh, [{\22batch\22}, {}]>"}, mhlo.sharding = "{devices=[2,1]<=[2]}", ttcore.argument_type = #ttcore.argument_type<parameter>}, %arg2: tensor<2560xbf16> {mhlo.frontend_attributes = {xla.sdy.sharding = "#sdy.sharding<@mesh, [{}]>"}, mhlo.sharding = "{replicated}", ttcore.argument_type = #ttcore.argument_type<parameter>}) -> tensor<1x32x2560xbf16> {
  %0 = stablehlo.reshape %arg2 : (tensor<2560xbf16>) -> tensor<1x1x2560xbf16>
  %1 = stablehlo.reshape %0 : (tensor<1x1x2560xbf16>) -> tensor<2560xbf16>
  %2 = stablehlo.broadcast_in_dim %1, dims = [2] : (tensor<2560xbf16>) -> tensor<1x32x2560xbf16>
  %3 = stablehlo.reshape %2 : (tensor<1x32x2560xbf16>) -> tensor<32x2560xbf16>
  %4 = stablehlo.reshape %arg1 : (tensor<19456x2560xbf16>) -> tensor<1x19456x2560xbf16>
  %5 = stablehlo.reshape %4 : (tensor<1x19456x2560xbf16>) -> tensor<19456x2560xbf16>
  %6 = stablehlo.transpose %5, dims = [1, 0] {result_layout = dense<[0, 1]> : tensor<2xindex>, xla_shape = "bf16[2560,19456]{0,1}"} : (tensor<19456x2560xbf16>) -> tensor<2560x19456xbf16>
  %7 = stablehlo.dot_general %3, %6, contracting_dims = [1] x [0] : (tensor<32x2560xbf16>, tensor<2560x19456xbf16>) -> tensor<32x19456xbf16>
  %8 = stablehlo.reshape %7 : (tensor<32x19456xbf16>) -> tensor<1x32x19456xbf16>
  %9 = stablehlo.slice %8 [0:1, 0:32, 0:9728] : (tensor<1x32x19456xbf16>) -> tensor<1x32x9728xbf16>
  %10 = stablehlo.slice %8 [0:1, 0:32, 9728:19456] : (tensor<1x32x19456xbf16>) -> tensor<1x32x9728xbf16>
  %11 = stablehlo.multiply %9, %10 : tensor<1x32x9728xbf16>
  %12 = stablehlo.reshape %11 : (tensor<1x32x9728xbf16>) -> tensor<32x9728xbf16>
  %13 = stablehlo.transpose %arg0, dims = [1, 0] {result_layout = dense<[0, 1]> : tensor<2xindex>, xla_shape = "bf16[9728,2560]{0,1}"} : (tensor<2560x9728xbf16>) -> tensor<9728x2560xbf16>
  %14 = stablehlo.dot_general %12, %13, contracting_dims = [1] x [0] : (tensor<32x9728xbf16>, tensor<9728x2560xbf16>) -> tensor<32x2560xbf16>
  %15 = stablehlo.reshape %14 : (tensor<32x2560xbf16>) -> tensor<1x32x2560xbf16>
  return %15 : tensor<1x32x2560xbf16>
}
```

Error 
```
compiler/tt-mlir/test/test.mlir:17:11: error: 'stablehlo.slice' op inferred type(s) 'tensor<1x32x0xbf16>' are incompatible with return type(s) of operation 'tensor<1x32x4864xbf16>'
    %10 = stablehlo.slice %8 [0:1, 0:32, 9728:19456] : (tensor<1x32x19456xbf16>) -> tensor<1x32x9728xbf16>
          ^
compiler/tt-mlir/test/test.mlir:17:11: error: 'stablehlo.slice' op failed to infer returned types
    %10 = stablehlo.slice %8 [0:1, 0:32, 9728:19456] : (tensor<1x32x19456xbf16>) -> tensor<1x32x9728xbf16>
          ^
compiler/tt-mlir/test/test.mlir:17:11: note: see current operation: %11 = "stablehlo.slice"(%9) <{limit_indices = array<i64: 1, 32, 9728>, start_indices = array<i64: 0, 0, 9728>, strides = array<i64: 1, 1, 1>}> : (tensor<1x32x9728xbf16>) -> tensor<1x32x4864xbf16>
```

### PR DESCRIPTION
**Pull request by mmanzoorTT**
### Ticket
closes #6425 

### Problem description
Global to local shape updates for shardy op does not properly generate start indices for slice op

### What's changed
Generate correct start indices for slice op

### Checklist
- [X] New/Existing tests provide coverage for changes

### CODE REVIEW

File: lib/Dialect/StableHLO/Transforms/UpdateGlobalToLocalShapes.cpp [hunk 1]
```diff
@@ -102,6 +102,16 @@ static FailureOr<mlir::OperationState> createNewOperationState(
               }
 
               limitIndices[i] = *updatedLimitDim;
+
+              FailureOr<int64_t> updatedStartDim =
+                  shardy_utils::calculateUpdatedDim(
+                      globalMeshOp.getMesh(), shardings[0], startIndices[i]);
+              if (failed(updatedStartDim)) {
+                sliceOp->emitError(
+                  "Could not apply propagated tensor shardings for start indices of attribute dictionary for slice op");
```
Comment (hshahTT) [inline lib/Dialect/StableHLO/Transforms/UpdateGlobalToLocalShapes.cpp]: Nit: could you also change the error message on L99 to include a reference to "limit indices" (since this one mentions "start indices") so that the message is more helpful?

Comment (mmanzoorTT) [reply lib/Dialect/StableHLO/Transforms/UpdateGlobalToLocalShapes.cpp]: Thanks for the suggestion. updated.
