### PR TITLE
TTNN utils generate reshape fix

### LINKED ISSUE #1855: [TTNN] Utils function for inserting reshapes doesn't account for change in layout
A utils function in:
lib/Conversion/TTIRToTTNN/Utils.cpp

```C++
ttnn::ReshapeOp generateReshape(Value input, ArrayRef<int64_t> newShape,
                                PatternRewriter &rewriter)
```

Once reshape op is executed, the output shape is changed, hence we need to account for that change in output layout.

### PR DESCRIPTION
**Pull request by sdjordjevicTT**
A utils function in:
lib/Conversion/TTIRToTTNN/Utils.cpp
```C++
ttnn::ReshapeOp generateReshape(Value input, ArrayRef<int64_t> newShape,
                                PatternRewriter &rewriter);
```

It doesn't account for the output layout change of a reshaped op. This PR fixes the output layout of a newly generated reshape op.

Added a simple test to capture this.

Closes #1855

### CODE REVIEW

File: lib/Conversion/TTIRToTTNN/Utils.cpp [hunk 1]
```diff
@@ -9,10 +9,20 @@ namespace tt {
 namespace ttir_to_ttnn::utils {
 ttnn::ReshapeOp generateReshape(Value input, ArrayRef<int64_t> newShape,
```
Comment (azecevicTT) [inline lib/Conversion/TTIRToTTNN/Utils.cpp:10]: I would suggest we change the signature of this function to `(ArrayRef<int64_t> shape, Type elementType, Attribute encoding, PatternRewriter &rewriter)`. It's much more explicit and less error-prone, I believe it's currently used only in a few places so it shouldn't be a big change.

File: lib/Conversion/TTIRToTTNN/Utils.cpp [hunk 2]
```diff
@@ -9,10 +9,20 @@ namespace tt {
...
                                 PatternRewriter &rewriter) {
+  // With reshape op, the output layout changes due to new output shape, hence
+  // we need to create a new output layout attribute with the new shape.
   auto inputType = mlir::cast<RankedTensorType>(input.getType());
-  auto outputType = inputType.cloneWith(newShape, inputType.getElementType());
+  auto inputLayoutAttr =
```
Comment (azecevicTT) [inline lib/Conversion/TTIRToTTNN/Utils.cpp:15]: Is explicit cast to `ttnn::LayoutAttr` needed here, or will simple `inputType.getEncoding()` for tensor encoding be sufficient?

**Review by azecevicTT — APPROVED** [review]
Good catch, because it's already an existing function it can go as-is, but consider a comment.

File: lib/Conversion/TTIRToTTNN/Utils.cpp (hunk 1 above)
Comment (sdjordjevicTT) [reply lib/Conversion/TTIRToTTNN/Utils.cpp:10]: I am thinking about this, but either way, we will need input value in order to create a reshape op, right?

File: lib/Conversion/TTIRToTTNN/Utils.cpp (hunk 2 above)
Comment (sdjordjevicTT) [reply lib/Conversion/TTIRToTTNN/Utils.cpp:15]: I am using the TTNNLayoutAttr helper function to create the same layout but only with a new shape, hence I need input TTNNLayoutAttr:
 ```C++
inputLayoutAttr.withTensorShape(...)
```

File: lib/Conversion/TTIRToTTNN/Utils.cpp (hunk 1 above)
Comment (azecevicTT) [reply lib/Conversion/TTIRToTTNN/Utils.cpp:10]: You're right. In that case `mlir::TypedValue<mlir::RankedTensorType>` might be a better candidate for an input than just `Value` that we cast to `mlir::RankedTensorType` anyway in the first function statement.

File: lib/Conversion/TTIRToTTNN/Utils.cpp (hunk 2 above)
Comment (azecevicTT) [reply lib/Conversion/TTIRToTTNN/Utils.cpp:15]: Yeah, I see it now, the question is would standard `RankedTensorType::get(shape, elementType, encoding)` work in this case, if that's the case then it's better to use it because it's a standard way to handle these cases in the code.

File: lib/Conversion/TTIRToTTNN/Utils.cpp (hunk 1 above)
Comment (sdjordjevicTT) [reply lib/Conversion/TTIRToTTNN/Utils.cpp:10]: Yeah, I agree with that, will change it!

File: lib/Conversion/TTIRToTTNN/Utils.cpp (hunk 2 above)
Comment (sdjordjevicTT) [reply lib/Conversion/TTIRToTTNN/Utils.cpp:15]: I agree, but unfortunately, it won't work. RankedTensorType is a LLVM type and the encoding represents any attribute attached to it. RankedTensorType doesn't know how to update encoding based on the supplied shape and elementType.
