### PR TITLE
fixing const-eval with quantize (quantize ttnn -> flatbuffer)

### LINKED ISSUE #3505: Get const-eval to work with quant/dequant/requant
### Describe the bug

After https://github.com/tenstorrent/tt-mlir/pull/2990 is in, delete the workaround of const_eval set to false

### Steps to reproduce the issue

_No response_

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by anuragsingh-tt**
### Ticket
Fixes #3505 

The scale and zero point for quantization are inside constants and should be extracted as scalars in the per-tensor case. As such we need to enter into the const-eval function and go through the const-eval chain (walk through typecast (optional) -> to_device -> to_layout -> from_device) to reach the scalar value. This PR adds the logic for entering the const-eval function and continuing with the search.

### CODE REVIEW

File: lib/Target/TTNN/TTNNToFlatbuffer.cpp [hunk 1]
```diff
@@ -1009,6 +1009,29 @@ template <typename AttrType>
...
   mlir::Value firstInput = tensorVal;
+  // Recurse into the generated function for const-eval path.
+  if (mlir::tt::ttcore::LoadCachedOp loadCached =
+          firstInput.getDefiningOp<mlir::tt::ttcore::LoadCachedOp>()) {
+    mlir::FlatSymbolRefAttr symbolRef = loadCached.getCalleeAttr();
+    mlir::ModuleOp moduleOp = loadCached->getParentOfType<mlir::ModuleOp>();
+    mlir::func::FuncOp funcOp =
+        mlir::SymbolTable::lookupNearestSymbolFrom<mlir::func::FuncOp>(
+            moduleOp, symbolRef.getAttr());
+    if (!funcOp || funcOp.getNumArguments() > 0 || funcOp.getBody().empty()) {
```
Comment (vwellsTT) [inline lib/Target/TTNN/TTNNToFlatbuffer.cpp]: I think `assert` would be more idiomatic than `if(...) unreachable` here

File: lib/Target/TTNN/TTNNToFlatbuffer.cpp [hunk 2]
```diff
@@ -1009,6 +1009,29 @@ template <typename AttrType>
...
+      llvm_unreachable("Invalid const-eval function structure.");
+    }
+    mlir::Block &entryBlock = funcOp.getBody().front();
+    mlir::Operation *terminator = entryBlock.getTerminator();
+    if (mlir::func::ReturnOp returnOp =
+            mlir::dyn_cast<mlir::func::ReturnOp>(terminator)) {
+      if (returnOp.getNumOperands() != 1) {
```
Comment (vwellsTT) [inline lib/Target/TTNN/TTNNToFlatbuffer.cpp]: same here

File: lib/Target/TTNN/TTNNToFlatbuffer.cpp [hunk 3]
```diff
@@ -1009,6 +1009,29 @@ template <typename AttrType>
 static AttrType getAttrFromConstantChain(mlir::Value tensorVal,
                                          const char *expectedTypeMsg) {
   mlir::Value firstInput = tensorVal;
+  // Recurse into the generated function for const-eval path.
```
Comment (vwellsTT) [inline lib/Target/TTNN/TTNNToFlatbuffer.cpp:1012]: Hmm, I think you should update the comment above this function too.  But I'm not sure I understand exactly what the use-case is here, you're trying to add logic s.t. we can detect constants which get hoisted to const-eval specifically with this func I guess?  Could you perhaps provide more details in PR description or something?

Comment (anuragsingh-tt) [reply lib/Target/TTNN/TTNNToFlatbuffer.cpp:1012]: The scale and zero point for quantization are inside constants and should be extracted as scalars in the per-tensor case. As such we need to enter into the const-eval function and go through the const-eval chain (walk through typecast (optional) -> to_device -> to_layout -> from_device) to reach the scalar value. This PR adds the logic for entering the const-eval function and continuing with the search.

Comment (vwellsTT) [reply lib/Target/TTNN/TTNNToFlatbuffer.cpp:1012]: I see, makes sense.  Thanks!
