### PR TITLE
Skip deallocation of conv2d activation when it is overridden

### LINKED ISSUE #3383: Conv2d Deallocate activation fails in ttmlir runtime
### Describe the bug

```
            RuntimeTTNN |    DEBUG | Executing operation: %35 = "ttnn.conv2d"(%33, %34, %0) <{batch_size = 8 : i32, conv2d_config = #ttnn.conv2d_config<input_channels_alignment = 32, deallocate_activation = true, act_block_h_override = 32, reshard_if_not_optimal = false, enable_split_reader = false>, dilation = array<i32: 1, 1>, groups = 1 : i32, in_channels = 64 : i32, input_height = 56 : i32, input_width = 56 : i32, kernel_size = array<i32: 3, 3>, out_channels = 64 : i32, padding = array<i32: 1, 1>, stride = array<i32: 1, 1>}> : (tensor<1x1x25088x64xbf16, #ttnn.ttnn_layout<(d0, d1, d2, d3) -> (d0 * 25088 + d1 * 25088 + d2, d3), <61x1, (d0, d1) -> (0, d0 floordiv 8, d0 mod 8)>, memref<13x2x!tt.tile<32x32, bf16>, #ttnn.buffer_type<l1>>, <height_sharded>>>, tensor<1x1x576x64xbf16, #ttnn.ttnn_layout<(d0, d1, d2, d3) -> (d0 * 576 + d1 * 576 + d2, d3), <8x8, (d0, d1) -> (0, d0, d1)>, memref<3x1x!tt.tile<32x32, bf16>, #ttnn.buffer_type<dram>>, <interleaved>>>, !ttnn.device) -> tensor<1x1x25088x64xbf16, #ttnn.ttnn_layout<(d0, d1, d2, d3) -> (d0 * 25088 + d1 * 25088 + d2, d3), <61x1, (d0, d1) -> (0, d0 floordiv 8, d0 mod 8)>, memref<13x2x!tt.tile<32x32, bf16>, #ttnn.buffer_type<l1>>, <height_sharded>>> loc("resnet50_30_samples_2.mlir.ttnn":197:15)
                 Always |  WARNING | Golden information not found
            RuntimeTTNN |    DEBUG | Executing operation: "ttnn.deallocate"(%34) <{force = false}> : (tensor<1x1x576x64xbf16, #ttnn.ttnn_layout<(d0, d1, d2, d3) -> (d0 * 576 + d1 * 576 + d2, d3), <8x8, (d0, d1) -> (0, d0, d1)>, memref<3x1x!tt.tile<32x32, bf16>, #ttnn.buffer_type<dram>>, <interleaved>>>) -> () loc("resnet50_30_samples_2.mlir.ttnn":198:9)
                 Always |  WARNING | Golden information not found
            RuntimeTTNN |    DEBUG | Executing operation: "ttnn.deallocate"(%33) <{force = false}> : (tensor<1x1x25088x64xbf16, #ttnn.ttnn_layout<(d0, d1, d2, d3) -> (d0 * 25088 + d1 * 25088 + d2, d3), <61x1, (d0, d1) -> (0, d0 floordiv 8, d0 mod 8)>, memref<13x2x!tt.tile<32x32, bf16>, #ttnn.buffer_type<l1>>, <height_sharded>>>) -> () loc("resnet50_30_samples_2.mlir.ttnn":199:9)
                 Always |    FATAL | 
DEBUG_ASSERT @ /localdev/rpavlovicL/tt-mlir/runtime/lib/ttnn/types/types.cpp:79: ttnnTensor.is_allocated()
```

if conv2d deallocated activation, and we tried to deallocate explicitly tensor we will hit this assert in runtime 
```
DEBUG_ASSERT @ /localdev/rpavlovicL/tt-mlir/runtime/lib/ttnn/types/types.cpp:79: ttnnTensor.is_allocated()
backtrace:
 --- tt::runtime::ttnn::ProgramTensorPool::getRuntimeTensorAndValidate(tt::target::ttnn::TensorRef const*) const
 --- tt::runtime::ttnn::ProgramTensorPool::getTTNNTensorWrapperAndValidate(tt::target::ttnn::TensorRef const*) const
 --- tt::runtime::ttnn::ProgramTensorPool::getTTNNTensorWrapperAndValidate(tt::target::ttnn::TensorRef const*)
 --- tt::runtime::ttnn::operations::deletion::run(tt::target::ttnn::DeallocateOp const*, tt::runtime::ttnn::ProgramContext&)
 --- tt::runtime::ttnn::ProgramExecutor::runOperation(tt::target::ttnn::Operation const*)
 --- tt::runtime::ttnn::ProgramExecutor::execute()
```

### PR DESCRIPTION
**Pull request by vkovacevicTT**
### Ticket
Closes #3383

### Problem description
When overriding `dellocate_activation` parameter in Conv2dConfig, a `ttnnTensor.is_allocated()` error may occur in runtime due to a deallocate op for conv2d activation already being added in the `TTNNDeallocate` pass.

### What's changed
- `ttnn.deallocate` will not be added in `TTNNDeallocate` pass for conv2d op activation if `deallocate_activation` parameter is set to `true`.
- added a test `test/ttmlir/Silicon/TTNN/n150/deallocate_override.mlir`
- (_not related to the issue_) changed `test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir` to be more flexible if new conv2d config parameters are added

### CODE REVIEW

File: lib/Dialect/TTNN/Transforms/Passes.cpp [hunk 1]
```diff
@@ -132,6 +132,20 @@ class TTNNDeallocate : public impl::TTNNDeallocateBase<TTNNDeallocate> {
             continue;
           }
 
+          // Don't deallocate the activation after conv2d op if
+          // 'deallocate_activation' Conv2dConfig override is set to true.
+          if (auto conv2dOp = mlir::dyn_cast<ttnn::Conv2dOp>(lastOp)) {
+            // Check if result is an activation (first operand of conv2d op) &&
+            // check if deallocate_activation is set to true
+            if (conv2dOp->getOperand(0) == result &&
```
Comment (azecevicTT) [inline lib/Dialect/TTNN/Transforms/Passes.cpp:140]: Why not `.getInput()`, instead of `->getOperand(0)`, in that case you wouldn't need to explain what `operand(0)` is (generally that whole comment becomes redundant).

File: lib/Dialect/TTNN/Transforms/Passes.cpp [hunk 2]
```diff
@@ -132,6 +132,20 @@ class TTNNDeallocate : public impl::TTNNDeallocateBase<TTNNDeallocate> {
...
+                conv2dOp.getConv2dConfigAttr() &&
+                conv2dOp.getConv2dConfigAttr()
+                    .getDeallocateActivation()
+                    .getValue()) {
```
Comment (azecevicTT) [inline lib/Dialect/TTNN/Transforms/Passes.cpp:144]: This might works for your use case for now (if I remember correctly you're setting all values explicitly if `Conv2dConfig` is provided), but if you look at the definition of an attribute it's an optional attr, so this is equivalent to dereferencing `nullptr` in some cases. You should add `conv2dOp.getConv2dConfigAttr().getDeallocateActivation() && this_cond`.

**Review by azecevicTT — COMMENTED** [review]
Can you add some test cases that verify this?

**Review by rpavlovicTT — APPROVED** [review]

File: lib/Dialect/TTNN/Transforms/Passes.cpp [hunk 3]
```diff
@@ -132,6 +132,19 @@ class TTNNDeallocate : public impl::TTNNDeallocateBase<TTNNDeallocate> {
             continue;
           }
 
+          // Don't deallocate the activation after conv2d op if
+          // 'deallocate_activation' Conv2dConfig override is set to true.
```
Comment (rpavlovicTT) [inline lib/Dialect/TTNN/Transforms/Passes.cpp:136]: Doesn't have to be override, it could be chosen by optimizer.

**Review by mtopalovicTT — APPROVED** [review]
@vkovacevicTT What do we gain from adding `deallocate_activation = true`? When does conv release this memory?
It would be good to add check (or item but with higher priority) to verifier of conv also which checks that there are no users of activation downstream if `deallocate_activation` is set.

**Review by jserbedzijaTT — APPROVED** [review]

**Comment by odjuricicTT** [comment]
> What do we gain from adding deallocate_activation = true? When does conv release this memory?

@mtopalovicTT Conv consista of at least a halo op followed by conv internal ops. Decallocate activation flag does so after halo op, so that more memory is left for conv internal.
