### PR TITLE
[TTIRToD2M] Fix higher-rank matmul collapsing

### LINKED ISSUE #6648: [d2m] Support higher rank matmul
Higher rank RHS matmuls incorrectly collapse:
```mlir
  func.func @component_1_ttir_dot_general_41(%arg0: tensor<32x8x1x128xbf16>, %arg1: tensor<32x8x128x128xbf16>) -> tensor<32x8x1x128xbf16> {
    %0 = "ttir.dot_general"(%arg0, %arg1) <{batch_dims_lhs = array<i64: 0, 1>, batch_dims_rhs = array<i64: 0, 1>, contract_dims_lhs = array<i64: 3>, contract_dims_rhs = array<i64: 2>}> : (tensor<32x8x1x128xbf16>, tensor<32x8x128x128xbf16>) -> tensor<32x8x1x128xbf16>
    return %0 : tensor<32x8x1x128xbf16>
  }
```

```
error: 'd2m.generic' op shard shape mismatch between operand[0] shard_shape=[8192, 128] and operand[1] shard_shape=[32768, 128] at affine dim d2
    %0 = "ttir.dot_general"(%arg0, %arg1) <{batch_dims_lhs = array<i64: 0, 1>, batch_dims_rhs = array<i64: 0, 1>, contract_dims_lhs = array<i64: 3>, contract_dims_rhs = array<i64: 2>}> : (tensor<32x8x1x128xbf
16>, tensor<32x8x128x128xbf16>) -> tensor<32x8x1x128xbf16>
```

I think we'd not want to collapse in this case.

### PR DESCRIPTION
**Pull request by nsmithtt**
Higher-rank matrix multiplication operations (e.g., 4D tensors like [32,8,1,128] x [32,8,128,128]) were being incorrectly collapsed to 2D during the TTIRToD2M transformation, causing shard shape mismatches where batch dimensions were lost.

Root Cause:
The D2MMatmulRewriter only handled 2D matmuls and called toLayoutOperandsAndResults without noCollapse, causing higher-rank tensors to collapse when collapseTensors=true.

Changes:
1. Modified D2MMatmulRewriter::matchAndRewrite to detect higher-rank matmuls (rank > 2) and set noCollapse=true to preserve batch dimensions
2. Updated checkPreconditions to validate rank >= 2 and ensure both operands have matching ranks
3. Updated getAffineMapsArray to handle batch dimensions with identity mapping while preserving standard matmul semantics for the last two dimensions
4. Updated getIteratorTypesArray to mark batch dimensions as parallel iterators
5. Added comprehensive documentation for the affine map and iterator type generation logic

Testing:
- Added matmul_higher_rank.mlir with tests for 2D, 3D, and 4D matmuls
- All existing TTIRToD2M tests pass (backward compatible)
- Full compiler test suite passes (1091/1091 tests)

Closes #6648

### CODE REVIEW

File: lib/Conversion/TTIRToD2M/TTIRToD2M.cpp [hunk 1]
```diff
@@ -1136,29 +1144,112 @@ class D2MMatmulRewriter final
...
     assert(arity == 3 && "expected 3 operands");
-    // TODO(#2592) handle higher ranks, if needed in this pass.
-    assert(rank == 2 && "expected a rank 2 operation");
+    assert(rank >= 2 && "matmul operation must have rank >= 2");
     mlir::MLIRContext *ctx = builder.getContext();
 
-    return SmallVector<mlir::AffineMap>{makeAffineMap(ctx, {0, 2}),
-                                        makeAffineMap(ctx, {2, 1}),
-                                        makeAffineMap(ctx, {0, 1})};
+    // Handle 2D case specially for backward compatibility
```
Comment (vwellsTT) [inline lib/Conversion/TTIRToD2M/TTIRToD2M.cpp]: nit: end punctuation on this + subsequent comments here

Comment (vwellsTT) [reply lib/Conversion/TTIRToD2M/TTIRToD2M.cpp]: I'm not sure I get why this special case is needed vs below, what does it do for backward compat vs below code on 2D?  Seems like the for loop would short circuit and we'd get same values if rank=2? (AI slop? :) )

Comment (nsmithtt) [reply lib/Conversion/TTIRToD2M/TTIRToD2M.cpp]: Gah, thanks for catching this, I noticed it too, I removed this case the code below should be strictly more general.

Comment (vwellsTT) [reply lib/Conversion/TTIRToD2M/TTIRToD2M.cpp]: Yeah I feel like my Claude-code always does this exact pattern, super annoyingly, haha

File: runtime/python/CMakeLists.txt [hunk 2]
```diff
@@ -89,6 +89,7 @@ if (TTMLIR_ENABLE_RUNTIME)
       ${PROJECT_BINARY_DIR}/include/ttmlir/Target/Common
       ${PROJECT_SOURCE_DIR}/runtime/python/include
   )
+  target_include_directories(_mlir_runtime_utils SYSTEM PRIVATE "$<BUILD_INTERFACE:${TTMETAL_INCLUDE_DIRS}>")
```
Comment (jameszianxuTT) [inline runtime/python/CMakeLists.txt]: I think this addition is unnecessary, since the included TTRuntimeTTNNUtils lib already includes this path as PUBLIC - https://github.com/tenstorrent/tt-mlir/blob/addf7c827d054da6b55af4e69fc485292391a33d/runtime/lib/ttnn/utils/CMakeLists.txt#L19

Comment (jameszianxuTT) [reply runtime/python/CMakeLists.txt]: Also I don't have a ton of context around the d2m execution path; From my reading it looks like a reasonable solution to the problem though someone else should probably look as well. 

I approve to unblock runtime changes, though I suggest these runtime changes are not added in the first place as the TTRuntimeTTNNUtils is already transitively including this dependency and I don't see why we want to include it twice, especially as the build is fine as it is

Comment (nsmithtt) [reply runtime/python/CMakeLists.txt]: I'll remove it then, we seem to be fine without it
