### PR TITLE
conv2d_transpose

### LINKED ISSUE #3267: [Stablehlo] conv_transpose2d op
Stablehlo has `convolution` op which is used for both `conv2d` and `conv_transpose2d` op. Currently, `stablehlo.convolution` is lowered to `ttir.convolution` and then lowered to `ttir.conv2d` op. This results in incorrect lowering of `conv_transpose2d` to `conv2d` op. 

Fix ttir->ttir decomposition and lower `ttir.convolution` to either `ttir.conv2d` or `ttir.conv_transpose2d` op.

### PR DESCRIPTION
**Pull request by mmanzoorTT**
### Ticket
closes #3267 

### Problem description
Stablehlo has `convolution` op which is used for both `conv2d` and `conv_transpose2d` op.
Currently, `stablehlo.convolution` is lowered to `ttir.convolution` and
then always decomposed to `ttir.conv2d` op (TTIRToTTIRDecomposition pass).
This results in incorrect lowering of `conv_transpose2d` to `conv2d` op. 

### What's changed
Lower `ttir.convolution` to either `ttir.conv2d` or `ttir.conv_transpose2d` op in TTIRToTTIRDecomposition pass.

### Checklist
- [X] New/Existing tests provide coverage for changes

### CODE REVIEW

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 1]
```diff
@@ -810,6 +810,16 @@ class StableHLOToTTIRConvolutionOpConversionPattern
...
 
+    bool isTransposed = false;
+    if (dimNums.getKernelInputFeatureDimension() != 0 &&
+        dimNums.getKernelOutputFeatureDimension() != 1 &&
+        dimNums.getInputSpatialDimensions() !=
+            dimNums.getKernelSpatialDimensions() &&
+        dimNums.getOutputSpatialDimensions() !=
+            dimNums.getKernelSpatialDimensions()) {
+      isTransposed = true;
+    }
```
Comment (svuckovicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:821]: Add a comment explaining how a transposed conv is detected.

File: lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp [hunk 2]
```diff
@@ -408,21 +418,63 @@ struct ConvolutionToConv2dPattern : public ConvolutionDecompositionPattern {
...
+      newConv = ttir::utils::createDPSOp<ttir::ConvTranspose2dOp>(
+          rewriter, op->getLoc(), outputType, Value(input), Value(weight),
+          adaptor.getBias(), inputDilationAttr, paddingAttr, outerPaddingAttr,
+          dilationAttr, groupsAttr);
+    } else {
+      newConv = ttir::utils::createDPSOp<ttir::Conv2dOp>(
+          rewriter, op.getLoc(), outputType, Value(input), Value(weight),
+          adaptor.getBias(), strideAttr, paddingAttr, dilationAttr, groupsAttr,
+          /*flattenedCompatInfo=*/nullptr);
+    }
```
Comment (svuckovicTT) [inline lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp:477]: Looks like there's some implementation-specific details being handled here. Can you add a comment explaining what's happening and why?

Comment (mmanzoorTT) [reply lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp]: Torch-MLIR lowering of `torch.conv_transpose2d` -> `stalehlo.convolution` uses padding attribute to represent both `padding` and `output_padding` and It is computed as 
```
for (int i = 0; i < nSpatialDims; ++i) {
      int64_t padInt = dilation[i] * (weightShape[i + 2] - 1) - padding[i];
      stablehloPaddingVec[i * 2] = padInt;
      stablehloPaddingVec[i * 2 + 1] =
          padInt + outputPadding[outputPadding.size() - i - 1];
    }
```

`padInt` is computed and stored as left element in padding matrix. `output_padding` is added with the computed `padInt` for right element in the padding matrix. 
So left element is subtracted from right to find out the output_padding and reverse of `padInt` computation is used to determine padding attribute.

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp (hunk 1 above)
Comment (mmanzoorTT) [reply lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp]: Torch-MLIR (https://github.com/llvm/torch-mlir/blob/main/lib/Conversion/TorchToStablehlo/Linear.cpp) creation of `DimensionNumberAttr` for `stablehlo.convolution` op. Following attributes are used to differentiate between normal and transposed convolution
- kernelInputFeatureDimension
- kernelOutputFeatureDimension
- inputFeatureDimension
- outputFeatureDimension
- kernelFeatureDimension

For normal convolution
```
stablehlo::ConvDimensionNumbersAttr dimensionNumbers =
        stablehlo::ConvDimensionNumbersAttr::get(
            /*context=*/rewriter.getContext(), /*inputBatchDimension=*/0,
            /*inputFeatureDimension=*/1,
            /*inputSpatialDimensions=*/spatialDimensions,
            /*kernelInputFeatureDimension=*/1,
            /*kernelOutputFeatureDimension=*/0,
            /*kernelSpatialDimensions=*/spatialDimensions,
            /*outputBatchDimension=*/0, /*outputFeatureDimension=*/1,
            /*outputSpatialDimensions=*/spatialDimensions);
```
For transposed convolution 
```
stablehlo::ConvDimensionNumbersAttr dimensionNumbers =
        stablehlo::ConvDimensionNumbersAttr::get(
            /*context=*/rewriter.getContext(), /*inputBatchDimension=*/0,
            /*inputFeatureDimension=*/1,
            /*inputSpatialDimensions=*/spatialDims,
            /*kernelInputFeatureDimension=*/nDims - 1,
            /*kernelOutputFeatureDimension=*/nDims - 2,
            /*kernelSpatialDimensions=*/transposedSpatialDims,
            /*outputBatchDimension=*/0, /*outputFeatureDimension=*/1,
            /*outputSpatialDimensions=*/spatialDims);
```

Comment (svuckovicTT) [reply lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp]: Ah, they're using the weights shape to determine this, if I understand correctly?

```C++
    // The input shape is [N, C, H, W]
    auto inputTy = cast<RankedTensorType>(input.getType());
    // The weight shape is [OC, (IC//G), KH, KW]
    // If transposed is set to true,
    // the weight shape changes to [IC, (OC//G), KH, KW]
```

If so, writing this as a comment would be very useful for anyone coming into it later. A good practice I learned from stackoverflow guidelines is to always copy the content from the source one is quoting - if the link breaks (e.g. they move the file), the comment would still stay relevant.

**Review by svuckovicTT — APPROVED** [review]

File: include/ttmlir/Dialect/TTIR/IR/TTIROps.td [hunk 3]
```diff
@@ -1499,15 +1499,15 @@ def TTIR_ConvolutionOp : TTIR_NamedOp<"convolution"> {
...
     DenseI64ArrayAttr:$window_strides,
     DenseI64ArrayAttr:$padding,
     DenseI64ArrayAttr:$input_dilation,
     DenseI64ArrayAttr:$weight_dilation,
     DenseBoolArrayAttr:$window_reversal,
     TTIR_ConvolutionLayoutAttr:$convolution_layout,
     ConfinedAttr<I64Attr, [IntPositive]>:$feature_group_count,
-    ConfinedAttr<I64Attr, [IntPositive]>:$batch_group_count
+    ConfinedAttr<I64Attr, [IntPositive]>:$batch_group_count,
+    DefaultValuedAttr<BoolAttr, "false">:$is_transposed
```
Comment (azecevicTT) [inline include/ttmlir/Dialect/TTIR/IR/TTIROps.td:1510]: I might be wrong, but it seems to me that all parameters to calculate `is_transposed` are already presents, which makes `is_transposed` redundant parameter.

**Review by azecevicTT — CHANGES_REQUESTED** [review]

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 4]
```diff
@@ -810,6 +810,21 @@ class StableHLOToTTIRConvolutionOpConversionPattern
...
+    // transposed convolution, based on Torch-MLIR lowering patterns.
+    // https://github.com/llvm/torch-mlir/blob/main/lib/Conversion/TorchToStablehlo/Linear.cpp
+    if (dimNums.getKernelInputFeatureDimension() != 0 &&
+        dimNums.getKernelOutputFeatureDimension() != 1 &&
+        dimNums.getInputSpatialDimensions() !=
+            dimNums.getKernelSpatialDimensions() &&
+        dimNums.getOutputSpatialDimensions() !=
+            dimNums.getKernelSpatialDimensions()) {
+      isTransposed = true;
+    }
```
Comment (jserbedzijaTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:826]: As @azecevicTT said, you could move this logic to the TTIR dialect instead of introducing `isTransposed` flag.

File: include/ttmlir/Dialect/TTIR/IR/TTIROps.td (hunk 3 above)
Comment (mmanzoorTT) [reply include/ttmlir/Dialect/TTIR/IR/TTIROps.td]: Thanks. updated as suggested.

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp (hunk 4 above)
Comment (mmanzoorTT) [reply lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp]: updated.

**Review by azecevicTT — APPROVED** [review]
Let's wait on @jserbedzijaTT review on this as well before merging.

**Review by jserbedzijaTT — APPROVED** [review]
