### PR TITLE
Address sanitizer bugfix

### LINKED ISSUE #2831: `clamp_op_canonicalize.mlir` test ASAN failure: `AddressSanitizer: stack-use-after-scope`
`clamp_op_canonicalize.mlir` test ASAN failure: `AddressSanitizer: stack-use-after-scope`:

```
FAIL: TTMLIR :: ttmlir/Dialect/TTIR/canonicalize/clamp_op_canonicalize.mlir (371 of 816)                                                                                                                              
******************** TEST 'TTMLIR :: ttmlir/Dialect/TTIR/canonicalize/clamp_op_canonicalize.mlir' FAILED ********************                                                                                         
Exit Code: 2                                                                                                                                                                                                          
                                                                                                                                                                                                                      
Command Output (stderr):                                                                                                                                                                                              
--                                                                                                                                                                                                                    
RUN: at line 1: /Users/nsmith/src/tt-mlir/build_main_asan/bin/ttmlir-opt -canonicalize /Users/nsmith/src/tt-mlir/test/ttmlir/Dialect/TTIR/canonicalize/clamp_op_canonicalize.mlir | /opt/ttmlir-toolchain/bin/FileChec
k /Users/nsmith/src/tt-mlir/test/ttmlir/Dialect/TTIR/canonicalize/clamp_op_canonicalize.mlir                                                                                                                          
+ /Users/nsmith/src/tt-mlir/build_main_asan/bin/ttmlir-opt -canonicalize /Users/nsmith/src/tt-mlir/test/ttmlir/Dialect/TTIR/canonicalize/clamp_op_canonicalize.mlir                                                   
+ /opt/ttmlir-toolchain/bin/FileCheck /Users/nsmith/src/tt-mlir/test/ttmlir/Dialect/TTIR/canonicalize/clamp_op_canonicalize.mlir
=================================================================                                          
==97132==ERROR: AddressSanitizer: stack-use-after-scope on address 0x00016d9f48f0 at pc 0x0001035f437c bp 0x00016d9f4550 sp 0x00016d9f4548                                                      
READ of size 8 at 0x00016d9f48f0 thread T0                                                                                                                                                                            
    #0 0x1035f4378 in llvm::SmallVector<long long, CalculateSmallVectorDefaultInlinedElements<long long>::value> ttmlir::utils::getBroadcastDimensions<long long>(llvm::ArrayRef<long long>, llvm::ArrayRef<long long>
) Utils.h:234                                                                                                                                                                                                         
    #1 0x106623b7c in ttmlir::utils::broadcastValue(mlir::PatternRewriter&, mlir::Value, mlir::RankedTensorType, mlir::Value&, mlir::Location, bool) Utils.h:546                                                      
    #2 0x106621904 in mlir::tt::ttir::ClampTensorOp::getCanonicalizationPatterns(mlir::RewritePatternSet&, mlir::MLIRContext*)::$_326::operator()(mlir::tt::ttir::ClampTensorOp, mlir::PatternRewriter&) const TTIROps
.cpp:193                                                                                                                                                                                                              
    #3 0x10662069c in mlir::tt::ttir::ClampTensorOp::getCanonicalizationPatterns(mlir::RewritePatternSet&, mlir::MLIRContext*)::$_326::__invoke(mlir::tt::ttir::ClampTensorOp, mlir::PatternRewriter&) TTIROps.cpp:172
    #4 0x10670c804 in mlir::RewritePatternSet& mlir::RewritePatternSet::add<mlir::tt::ttir::ClampTensorOp>(llvm::LogicalResult (*)(mlir::tt::ttir::ClampTensorOp, mlir::PatternRewriter&), mlir::PatternBenefit, llvm:
:ArrayRef<llvm::StringRef>)::FnPattern::matchAndRewrite(mlir::tt::ttir::ClampTensorOp, mlir::PatternRewriter&) const PatternMatch.h:914
    #5 0x10670c1a8 in mlir::detail::OpOrInterfaceRewritePatternBase<mlir::tt::ttir::ClampTensorOp>::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const PatternMatch.h:331
    #6 0x107faf3b0 in void llvm::function_ref<void ()>::callback_fn<mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function
_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>)::$_2>(long)+0x27c (ttmlir-opt:arm64+0x105ba73b0)
    #7 0x107faccc4 in mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::funct
ion_ref<llvm::LogicalResult (mlir::Pattern const&)>)+0x2d0 (ttmlir-opt:arm64+0x105ba4cc4)                                                                                                                             
    #8 0x107f94b58 in (anonymous namespace)::GreedyPatternRewriteDriver::processWorklist()+0x76c (ttmlir-opt:arm64+0x105b8cb58)                                                                                       
    #9 0x107f9439c in void llvm::function_ref<void ()>::callback_fn<(anonymous namespace)::RegionPatternRewriteDriver::simplify(bool*) &&::$_8>(long)+0x18 (ttmlir-opt:arm64+0x105b8c39c)
    #10 0x107f92c70 in mlir::applyPatternsGreedily(mlir::Region&, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig, bool*)+0x418 (ttmlir-opt:arm64+0x105b8ac70)                                        
    #11 0x107df26c8 in (anonymous namespace)::Canonicalizer::runOnOperation()+0xa8 (ttmlir-opt:arm64+0x1059ea6c8)
```

Repro, build with `CMAKE_BUILD_TYPE=Asan` and run test.

### PR DESCRIPTION
**Pull request by mmanzoorTT**
### Ticket
closes #2831 

### Problem description
Reassigning llvm::ArrayRef causing address sanitization error.

### What's changed
Use llvm::SmallVector instead which can be reassigned. 

### Checklist
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

File: include/ttmlir/Utils.h [hunk 1]
```diff
@@ -525,7 +525,8 @@ broadcastValue(mlir::PatternRewriter &rewriter, mlir::Value input,
                mlir::RankedTensorType desiredType, mlir::Value &output,
                mlir::Location loc, bool frontUnsqueeze) {
   auto inputType = mlir::cast<mlir::RankedTensorType>(input.getType());
-  auto inputShape = inputType.getShape();
+  llvm::SmallVector<int64_t> inputShape(inputType.getShape().begin(),
```
Comment (azecevicTT) [inline include/ttmlir/Utils.h:528]: Nit: `inputShape(inputType.getShape())`

**Review by azecevicTT — APPROVED** [review]

**Review by nsmithtt — APPROVED** [review]
+1 for Aleks' nit, thanks for the quick fix!

**Review by sdjordjevicTT — APPROVED** [review]
Thanks for the fix!
