### PR TITLE
Change L1_SMALL_SIZE to 64KB

### LINKED ISSUE #5556: UNet fails on tt-forge benchmarks with Optimizer enabled
VGG19_UNet fails on [tt-forge n150 benchmark](https://github.com/tenstorrent/tt-forge/actions/runs/18909064767/job/53974565107) when Optimizer is enabled with error:
```
RuntimeError: TT_FATAL @ /__w/tt-xla/tt-xla/third_party/tt-mlir/src/tt-mlir/third_party/tt-metal/src/tt-metal/tt_metal/impl/allocator/bank_manager.cpp:431: address.has_value()
info:
Out of Memory: Not enough space to allocate 16384 B L1_SMALL buffer across 64 banks, where each bank needs to store 256 B, but bank size is only 32768 B
```

Error disappears when  L1_SMALL_SIZE is increased to 64KB.

[ttnn.mlir.txt](https://github.com/user-attachments/files/23211282/ttnn.mlir.txt) with Optimizer enabled (ERROR).

[ttnn.mlir.txt](https://github.com/user-attachments/files/23211289/ttnn.mlir.txt) with Optimizer disabled (OK).

### PR DESCRIPTION
**Pull request by vkovacevicTT**
### Ticket
Closes #5556

### Problem description
UNet was failing on n150 tt-forge benchmark with Optimizer enabled.

### What's changed
Changed L1_SMALL_SIZE to 1 << 16.
Lowered CB size in `getOpRuntime` unit test for `UpdateCacheOp` that was failing due to very large CB.

### CODE REVIEW

**Comment by nvukobratTT** [comment]
Minor advice: Think about running this change through XLA nightly just in case. 

fyi @ppadjinTT

**Comment by vkovacevicTT** [comment]
Ran it on tt-forge perf benchmark for starters: https://github.com/tenstorrent/tt-xla/actions/runs/18907648892

File: include/Constants.h [hunk 1]
```diff
@@ -11,7 +11,7 @@ namespace tt::constants {
 
 // Default L1 small size to use for the ttnn runtime (32kb).
```
Comment (rpavlovicTT) [inline include/Constants.h]: update comment to reflect constant's value

**Comment by vkovacevicTT** [comment]
tt-xla nightly with this change: https://github.com/tenstorrent/tt-xla/actions/runs/19036271865
