### PR TITLE
Fix a segfault in ReduceWindowOp conversion

### LINKED ISSUE #2401: ReduceWindowOp can cause a segfault
Trying to compile a StableHLO reduce_window without a padding attribute segfaults
Example graph from a test inside tt-xla:
```mlir
func.func private @cumsum_0(%arg0: tensor<1x1xi32>) -> tensor<1x1xi32> {
    %c = stablehlo.constant dense<0> : tensor<i32>
    %0 = stablehlo.broadcast_in_dim %c, dims = [] : (tensor<i32>) -> tensor<i32>
    %1 = "stablehlo.reduce_window"(%arg0, %0) <{window_dimensions = array<i64: 1, 1>}> ({
    ^bb0(%arg1: tensor<i32>, %arg2: tensor<i32>):
      %2 = stablehlo.add %arg1, %arg2 : tensor<i32>
      stablehlo.return %2 : tensor<i32>
    }) : (tensor<1x1xi32>, tensor<i32>) -> tensor<1x1xi32>
    return %1 : tensor<1x1xi32>
  }
```

### PR DESCRIPTION
**Pull request by sgligorijevicTT**
### Ticket
fixes #2401 

### Problem description
We retrieve the padding attribute in two places but only guard against it not existing in one place.

### What's changed
Now we read the padding attribute only once and pass it down trough arguments to where it's needed. 

### Checklist
- [X] New/Existing tests provide coverage for changes

### CODE REVIEW

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 1]
```diff
@@ -1023,22 +1024,26 @@ class StableHLOToTTIRReduceWindowOpConversionPattern
...
     llvm::ArrayRef<int64_t> windowDimensions =
         adaptor.getWindowDimensionsAttr().asArrayRef();
-    mlir::DenseIntElementsAttr padding = adaptor.getPaddingAttr();
 
     // Validate padding size
     if (padding.size() != (inputRank * 2)) {
       return false;
     }
 
+    auto padding_elems = padding.asArrayRef();
```
Comment (mmanzoorTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:1040]: Nit: snake case

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 2]
```diff
@@ -1023,22 +1024,26 @@ class StableHLOToTTIRReduceWindowOpConversionPattern
...
+    auto first = padding_elems[0];
+
     // Check for splat padding (all zeroes expected).
-    if (padding.isSplat()) {
-      if (padding.getSplatValue<int64_t>() != 0) {
+    if (std::all_of(padding_elems.begin(), padding_elems.end(),
```
Comment (mmanzoorTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:1044]: please use llvm::all_of instead of std::all_op

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 3]
```diff
@@ -1023,26 +1025,30 @@ class StableHLOToTTIRReduceWindowOpConversionPattern
...
         adaptor.getWindowDimensionsAttr().asArrayRef();
-    mlir::DenseIntElementsAttr padding = adaptor.getPaddingAttr();
 
     // Validate padding size
     if (padding.size() != (inputRank * 2)) {
       return false;
     }
 
+    auto paddingElems = padding.asArrayRef();
+    auto first = paddingElems[0];
```
Comment (azecevicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:1042]: You can index `DenseI64ArrayAttr` directly.

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 4]
```diff
@@ -1023,26 +1025,30 @@ class StableHLOToTTIRReduceWindowOpConversionPattern
...
+
     // Check for splat padding (all zeroes expected).
-    if (padding.isSplat()) {
-      if (padding.getSplatValue<int64_t>() != 0) {
+    if (llvm::all_of(paddingElems,
```
Comment (azecevicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:1045]: `llvm::all_equal(padding)`

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 5]
```diff
@@ -1070,12 +1076,12 @@ class StableHLOToTTIRReduceWindowOpConversionPattern
...
   // Determine and validate dimension attribute for non-splat padding attribute.
   bool validateNonSplatPadding(llvm::ArrayRef<int64_t> windowDimensions,
-                               mlir::DenseIntElementsAttr padding,
+                               DenseI64ArrayAttr padding,
                                RankedTensorType inputType,
                                int64_t &dimension) const {
     int64_t dimArgValue = -1;
     int64_t idx = -1;
-    auto padding_values = padding.getValues<int64_t>();
+    auto paddingValues = padding.asArrayRef();
```
Comment (azecevicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:1084]: This is redundant as well.

**Review by azecevicTT — APPROVED** [review]

**Review by mmanzoorTT — APPROVED** [review]
