### PR TITLE
[optimizer] allow passing external device

### LINKED ISSUE #4232: Optimizer Overrides only run one successfully per python file
### Describe the bug

This is the [bug report](https://github.com/tenstorrent/tt-mlir/actions/runs/16452498991/job/46503307336?pr=4017).

Every time any optimizer overrides run in this file, the first one always works, the second one always fails regardless of the order of the overrides. Something is likely going wrong with the device reset. 

```
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DTTMLIR_ENABLE_RUNTIME=ON -DTT_RUNTIME_ENABLE_PERF_TRACE=ON -DTTMLIR_ENABLE_RUNTIME_TESTS=ON -DTTMLIR_ENABLE_STABLEHLO=ON -DTT_RUNTIME_DEBUG=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTTMLIR_ENABLE_OPMODEL=ON -DTTMLIR_ENABLE_PYKERNEL=ON
cmake --build build
cmake --build build -- ttrt
ttrt query --save-artifacts
export SYSTEM_DESC_PATH=$(pwd)/ttrt-artifacts/system_desc.ttsys
pytest test/python/golden/test_ttir_ops.py

/home/jgrim/wh-01-src/tt-mlir/lib/OpModel/TTNN/SingletonDeviceContext.cpp:33: static SingletonDeviceContext &mlir::tt::op_model::ttnn::SingletonDeviceContext::getInstance(): Assertion instance.m_device != nullptr' failed
```

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by pilkicTT**
Optimizer needs an open device to work - this causes issues in frontends where we need to close the device before running the `ttir-to-ttnn` pipeline and then re-open the device afterwards. New field is added in the pipeline options, allowing us to pass a device pointer to the optimizer. If the frontend doesn't pass the device pointer, the optimizer will (try to) open its own device.

The added field is not an `Option<T>`, since we do not want to parse it - for example when running the pipeline through the CLI. This means that, for now, we will not be able to use this mechanism in `tt-forge-fe` - due to the RTTI we cannot use the pipeline options struct directly. We'll need to figure out how to workaround this.

The `SingletonDeviceContext` class is refactored to allow for this. Additionally, the behaviour of the singleton is changed so that the lifetime of the device under it is managed fully by the users of the singleton. Even before this change, the situation with the singleton was a bit complex, since we allowed users to close the device manually, but opening of the device was done only during construction of the singleton. This caused issues if you wanted to run optimizer multiple times in a single process (#4232).

Asserts are in place to verify that the singleton is used properly. More info on this in the code comments.

Needed For tenstorrent/tt-xla#952
Closes #4232

### CODE REVIEW

**Review by mtopalovicTT — APPROVED** [review]

File: include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h [hunk 1]
```diff
@@ -7,48 +7,89 @@
...
   static void closeInstance();
 
+  // Sets an externally managed device. The device pointer must remain valid
+  // while the instance is using it. The instance will not attempt to close
+  // the device when `closeInstance()` is called - it will just clear the
+  // pointer.
+  //
+  // This is used when the device is passed to us by the frontend.
+  static void
+  setExternalDevice(::tt::tt_metal::distributed::MeshDevice *device);
```
Comment (sgholamiTT) [inline include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h]: This is just a suggestion:
If `SingletonDeviceContext` is "the" owner of `device`, is it possible to change the signature of this function to:
```c++
static void setExternalDevice(std::unique_ptr<::tt::tt_metal::distributed::MeshDevice> device);
```
Based on this comment of yours:
> _The device pointer must remain valid while the instance is using it._


I get this feeling that this code could potentially introduce some bugs. Eg.

```c++
{
  ::tt::tt_metal::distributed::MeshDevice device = initDevice(...);
  SingletonDeviceContext::setExternalDevice(&device);
} // here the `device` goes out of scope and it will be deleted. 
// So `SingletonDeviceContext` class stores a nullptr.
```

Comment (pilkicTT) [reply include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h]: as we've discussed offline - in the case of `setExternalDevice()` we do not own the device; this is used when a device pointer is passed (borrowed) from the frontends...

**Review by arminaleTT — APPROVED** [review]

**Review by rpavlovicTT — APPROVED** [review]
