### PR TITLE
Double persistent_intermediate_buffer size for reduce_scatter_minimal_async

### LINKED ISSUE #4712: CCL op regressions after legacy versions removed in metal
### Describe the bug

After metal uplift PR #4609 that uplifts https://github.com/tenstorrent/tt-metal/commit/1ccd1c6480 that removes legacy CCL ops, there were regressions in tt-mlir tests for reduce_scatter and all_gather.

This issue is for tracking PCC regressions due to this uplift in tt-mlir + frontend tests as well as re-enabling tests when issues are resolved.

### Steps to reproduce the issue
Run tt-torch and tt-xla CI on multichip devices to see low PCC
tt-torch: [[CI link]](https://github.com/tenstorrent/tt-torch/actions/runs/17286745952)
tt-xla: [[CI link]](https://github.com/tenstorrent/tt-xla/actions/runs/17286644489)

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by hkwonTT**
### Ticket
closes #4712

### Problem description
`reduce_scatter_minimal_async` with a linear topology requires a `persistent_intermediate_buffer` that is twice the input tensor size.

### What's changed
Increased the persistent_intermediate_buffer size by 2×.
Fixes the low-PCC issue observed with new CCL op.

### Checklist
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by AleksKnezevic** [comment]
Can we add an assert for this somewhere? tt-metal perhaps?

File: runtime/lib/ttnn/operations/ccl/reduce_scatter.cpp [hunk 1]
```diff
@@ -46,15 +46,19 @@ void run(const ::tt::target::ttnn::ReduceScatterOp *op,
 
   ::ttnn::Shape outputShape =
       operations::utils::toTTNNShape(*op->out()->desc()->shape());
-  ::ttnn::Shape inputShape =
-      operations::utils::toTTNNShape(*op->in()->desc()->shape());
+  // Line RS requires double-sized input for forward/backward
+  const auto &originalShape = *op->in()->desc()->shape();
+  std::vector<uint32_t> modifiedShape{2}; // Start with '2'
```
Comment (jnie-TT) [inline runtime/lib/ttnn/operations/ccl/reduce_scatter.cpp:51]: I agree with Aleks, can we create a ticket to model this in the compiler instead of doing this implicitly in runtime and hardcoding values? This way on the runtime side we can add an assert that if the ccl topology is `::ttnn::ccl::Topology::Linear` the intermediate buffer shape has to be double the input shape, it would also be great to have an assert on the metal side to be extra safe

Comment (hkwonTT) [reply runtime/lib/ttnn/operations/ccl/reduce_scatter.cpp:51]: https://github.com/tenstorrent/tt-mlir/issues/4758
I made an issue to track this.
reduce_scatter_minimal_async looks like a temporary workaround API. It will be cleaned up soon. https://github.com/tenstorrent/tt-metal/issues/25212
I will track the progress.
