### PR TITLE
Fix tensor.empty op conversion

### LINKED ISSUE #2659: [Stablehlo] tensor.empty op conversion failure
Stablehlo graph can contain `tensor.empty` op which didn't require any conversion (except type conversion). This conversion is affected after introducing [ttir.empty op](https://github.com/tenstorrent/tt-mlir/pull/2652). 

Sample graph to test `tensor.empty` op conversion.
```
func.func @test_empty_float() -> tensor<4x64xf32> {
    %0 = tensor.empty() : tensor<4x64xf32>
    return %0 : tensor<4x64xf32>
  }
```

The above graph should be converted to the below with stablehlo->ttir conversion pipeline.
```
func.func @test_empty_float() -> tensor<4x64xf32> {
    %0 = ttir.empty() : tensor<4x64xf32>
    return %0 : tensor<4x64xf32>
  }
```

### PR DESCRIPTION
**Pull request by mmanzoorTT**
### Ticket
closes #2659 

### Problem description
Stablehlo graph can contain `tensor.empty` op which didn't require any conversion (except type conversion). 
This conversion is affected after introducing `ttir.empty` op.

### What's changed
Convert tensor.empty op to ttir.empty op during Stablehlo to TTIR conversion.

### Checklist
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by nsmithtt — APPROVED** [review]
Thank you! Sorry, I guess search and replace messed up the original intention of the stablehlo test.

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp [hunk 1]
```diff
@@ -99,6 +99,7 @@ struct ConvertStableHLOToTTIRPass
 
     target.addIllegalDialect<mlir::stablehlo::StablehloDialect>();
     target.addIllegalDialect<mlir::sdy::SdyDialect>();
+    target.addIllegalOp<mlir::tensor::EmptyOp>();
```
Comment (mrakitaTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp:102]: I think we should just make it legal here and create a separate pass that converts `tensor->ttir` ops, it is much cleaner if each dialect to dialect conversion has its own pass, it also makes it reusable, and easier to spot bugs like this. I've added myself a note [here](https://github.com/tenstorrent/tt-mlir/issues/2421#issuecomment-2755356427) to do so, to not block this PR :)

**Review by mrakitaTT — APPROVED** [review]
Thank you for catching this Asif!

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp (hunk 1 above)
Comment (mmanzoorTT) [reply lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp:102]: The only reason to add this conversion pattern in here is to use the same `typeConverter`. but we can refactor `StableHLOToTTIRPass.cpp` and create a separate source file for `typeConverter` and shared among different conversion passes for `stablehlo to ttir pipeline`.

Comment (mrakitaTT) [reply lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp:102]: Big part of the current shlo type converter will be moved into data conversion pass in ttir and only shlo specific type conversion will be left here, so I am not sure it will be that reusable for arith/tensor dialects at that point.

**Review by azecevicTT — APPROVED** [review]
