### PR TITLE
Revert rope back to ttnn and introduce op constraints check for fusing

### LINKED ISSUE #6004: Phi models are failing with TT_FATAL: Input X dimension (32) must be divisible by 64 for tiling in TT-XLA
Ref : https://github.com/tenstorrent/tt-xla/issues/2290

Most of the Phi models are failing in nightly with the below error

`TT_FATAL: Input X dimension (32) must be divisible by 64 for tiling `

When bisected, it is observed that https://github.com/tenstorrent/tt-mlir/commit/de4bf473d51124392422dda751875fb9b1279ae9 is responsible for this error.

Tagging @mtopalovicTT as he is the author of this commit to fix this issue

### PR DESCRIPTION
**Pull request by mtopalovicTT**
closes #6004

This PR reverts fusing of rope to TTNN. This is simply because there are a lot of constraints in metal regarding rope fusing which simply cannot be checked in fusing itself. Instead we propose to use op model get constraints api to check if rope can be fused. This has some side effects:

* Rope can only be fused with optimizer on
* Rope tests now require op model which cases golden tests to fail because of https://github.com/tenstorrent/tt-mlir/issues/5283 https://github.com/tenstorrent/tt-mlir/issues/5909. Problem is that golden test are opening the device by default and caching it for all the tests that are being executed, but get constraints api also needs to open the device and asserts because device is already opened.

### CODE REVIEW

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp [hunk 1]
```diff
@@ -162,6 +167,275 @@ class TTNNMatmulAndLinearWithActivation : public mlir::OpRewritePattern<SrcOp> {
...
+// rotate_half([x1, x2, x3, x4]) = [-x3, -x4, x1, x2]
+//
+// This pattern is broken down into two sub-patterns:
+// 1. unrotatedProjection: matches x * cos
+// 2. rotatedProjection: matches rotate_half(x) * sin
+//
+// unrotatedProjection comes as following sequence of operations:
+// cos_unsqueezed = unsqueeze(cos) - where unsqueeze will be reshape which
+// prepends
+//  dimensions to cos to match x's rank.
```
Comment (rpavlovicTT) [inline lib/Dialect/TTNN/Transforms/TTNNFusing.cpp]: merge rows

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp [hunk 2]
```diff
@@ -162,6 +167,275 @@ class TTNNMatmulAndLinearWithActivation : public mlir::OpRewritePattern<SrcOp> {
...
+// unrotated_projection = multiply(x, cos_unsqueezed)
+//
+// rotatedProjections comes as following sequence of operations:
+// sin_unsqueezed = unsqueeze(sin) - where unsqueeze will be reshape which
+// prepends
+//  dimensions to sin to match x's rank.
```
Comment (rpavlovicTT) [inline lib/Dialect/TTNN/Transforms/TTNNFusing.cpp]: ditto

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp [hunk 3]
```diff
@@ -162,6 +167,275 @@ class TTNNMatmulAndLinearWithActivation : public mlir::OpRewritePattern<SrcOp> {
...
+    // Extract input layouts from the operation
+    std::vector<TTNNLayoutAttr> inputLayouts =
+        utils::extractInputLayouts(ropeOp.getOperation());
+
+    OpConfig config(mlir::cast<TTNNLayoutAttr>(resultType.getEncoding()));
+
+    auto backend = mlir::cast<OpModel>(ropeOp.getOperation());
+
+    llvm::Expected<ttnn::op_model::OpConstraints> constraintsExp =
+        backend.getOpConstraints(inputLayouts, config);
```
Comment (rpavlovicTT) [inline lib/Dialect/TTNN/Transforms/TTNNFusing.cpp]: You included OpConstraintValidation above, but did not use it here. Any specific reason?

**Comment by jameszianxuTT** [comment]
cc @ddilbazTT  @jazpurTT 

Will retrigger uplift to get this into tt-xla hopefully before nightly if this can be merged.

File: test/python/golden/optimizer/test_conv_sharding.py [hunk 4]
```diff
@@ -58,6 +58,8 @@ def test_conv2d_sharding(
     request,
     device,
 ):
+    print(device)
```
Comment (jserbedzijaTT) [inline test/python/golden/optimizer/test_conv_sharding.py]: I guess this is not needed

**Comment by mtopalovicTT** [comment]
> Looks good.
> 
> To confirm that with this PR and #6010 the microsoft phi regression will be solved? #6004

Even without eio fix it will work.

**Review by sdjordjevicTT — APPROVED** [review]

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp [hunk 5]
```diff
@@ -162,6 +167,273 @@ class TTNNMatmulAndLinearWithActivation : public mlir::OpRewritePattern<SrcOp> {
...
+
+    rewriter.replaceOp(srcOp, ropeOp.getResult());
+    return mlir::success();
+#else
+    return failure();
+#endif // TTMLIR_ENABLE_OPMODEL
+  }
+
+  bool matchUnrotatedProjection(MultiplyOp mulOp, Value &x,
+                                Value &cosUnsqueezed) const {
```
Comment (rpavlovicTT) [inline lib/Dialect/TTNN/Transforms/TTNNFusing.cpp:307]: Just suggestion, you don't have to apply it: in optimizer I used llvm::Expected for cases like this when you want to know if function failed/succeeded and returns some data along. In your example, it would be
```
llvm::Expected<pair<Value, Value>> matchUnrotatedProjection(MultiplyOp mulOp)
```
and you don't have to pass by ref x, cosUnsqueezed.

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp [hunk 6]
```diff
@@ -162,6 +167,273 @@ class TTNNMatmulAndLinearWithActivation : public mlir::OpRewritePattern<SrcOp> {
...
+    if (!inputType || inputType.getRank() < 1) {
+      return failure();
+    }
+
+    int64_t headDim = inputType.getShape()[inputType.getRank() - 1];
+    if (headDim <= 0 || headDim % 2 != 0) {
+      return failure();
+    }
+
+#ifdef TTMLIR_ENABLE_OPMODEL
```
Comment (rpavlovicTT) [inline lib/Dialect/TTNN/Transforms/TTNNFusing.cpp]: can whole `RoPEFusing` be enclosed by  `#ifdef TTMLIR_ENABLE_OPMODEL`?

File: lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp [hunk 7]
```diff
@@ -128,6 +128,38 @@ void createTTNNPipelineLoweringPasses(
...
+void createTTNNFusingPass(OpPassManager &pm,
+                          const TTIRToTTNNBackendPipelineOptions &options) {
+  if (options.enableFusing) {
+    if (options.optimizerPassEnabled) {
+#ifdef TTMLIR_ENABLE_OPMODEL
+      OptimizerPassesWrapperOptions wrapperOptions;
+      wrapperOptions.devicePtr = options.devicePtr;
+      wrapperOptions.tensorL1UsageCap = options.tensorL1UsageCap;
+
+      pm.addPass(createOptimizerPassesWrapper(
```
Comment (rpavlovicTT) [inline lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp]: We can maybe consider renaming this wrapper since now it wraps not only "optimizer" passes, but fusing too. Although, fusing may be considered an optimisation.

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp (hunk 3 above)
Comment (mtopalovicTT) [reply lib/Dialect/TTNN/Transforms/TTNNFusing.cpp]: I fixed it in latest commit.

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp (hunk 5 above)
Comment (mtopalovicTT) [reply lib/Dialect/TTNN/Transforms/TTNNFusing.cpp:307]: I don't mind either but we don't have that practice in dialect codebase. Lets for now stick to this :D

File: lib/Dialect/TTNN/Transforms/TTNNFusing.cpp (hunk 6 above)
Comment (mtopalovicTT) [reply lib/Dialect/TTNN/Transforms/TTNNFusing.cpp]: Yes

File: lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp (hunk 7 above)
Comment (mtopalovicTT) [reply lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp]: createExternalDeviceWrapper?

Comment (rpavlovicTT) [reply lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp]: maybe `createDeviceTouchingPassesWrapper`? since it's not exclusively external device.

Comment (mtopalovicTT) [reply lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp]: Hmmm I'm not sure about that one, maybe drop Touching?

File: include/ttmlir/Dialect/TTNN/Transforms/DevicePassWrapper.h [hunk 8]
```diff
@@ -35,19 +36,19 @@ struct OptimizerPassesWrapperOptions {
...
 //       [](OpPassManager &innerPm) {
 //         innerPm.addPass(createTTNNOptimizer(...));
 //         innerPm.addPass(createTTNNOperationValidationAndFallback(...));
 //       },
 //       options));
-std::unique_ptr<Pass> createOptimizerPassesWrapper(
-    std::function<void(OpPassManager &)> populatePipeline,
-    const OptimizerPassesWrapperOptions &options = {});
+std::unique_ptr<Pass>
+createDevicePassWrapper(std::function<void(OpPassManager &)> populatePipeline,
```
Comment (rpavlovicTT) [inline include/ttmlir/Dialect/TTNN/Transforms/DevicePassWrapper.h]: This is also fine, I'd just keep plural DevicePassesWrapper

Comment (mtopalovicTT) [reply include/ttmlir/Dialect/TTNN/Transforms/DevicePassWrapper.h]: Done
