### PR TITLE
Open Correctly Sized Device Depending on Flatbuffer

### LINKED ISSUE #3238: TT_FATAL thrown while running TTNN flatbuffer
### Describe the bug

TT_FATAL thrown while running TTNN flatbuffer

This flatbuffer contains the golden outputs for each operation.
A TT_FATAL was thrown during the golden output comparison.

Here is the ttrt log:
```

2025-05-07 02:41:43,969 - INFO - set log file=
2025-05-07 02:41:43,969 - INFO - setting artifacts folder path=/localdev/hkwon/working/single_fb_on_n300/ttrt-artifacts
2025-05-07 02:41:43,969 - DEBUG - ----------------------------starting run API----------------------------
2025-05-07 02:41:43,969 - DEBUG - ------preprocessing run API
2025-05-07 02:41:43,969 - DEBUG - ----------------------------starting query API----------------------------
2025-05-07 02:41:43,969 - DEBUG - ------preprocessing query API
2025-05-07 02:41:43,969 - DEBUG - ------finished preprocessing query API
2025-05-07 02:41:43,969 - DEBUG - ------checking constraints for query API
2025-05-07 02:41:43,969 - DEBUG - ------finished constraints for query API
2025-05-07 02:41:43,969 - DEBUG - ------executing query API
Warning: not importing testing submodule since project was not built with runtime testing enabled. To enable, rebuild with: -DTTMLIR_ENABLE_RUNTIME_TESTS=ON
2025-05-07 02:41:44,227 - DEBUG - getting system descriptor
  Detecting chips (found 2)
Read unexpected run_mailbox value: 0x40 (expected 0x80 or 0x0)
Read unexpected run_mailbox value: 0x40 (expected 0x80 or 0x0)
                 Always |    DEBUG | Device grid size = { 8, 8 }
2025-05-07 02:41:47,374 - DEBUG - ------finished executing query API
2025-05-07 02:41:47,374 - DEBUG - ------postprocessing query API
2025-05-07 02:41:47,374 - INFO - PASS: getting system_desc passed
2025-05-07 02:41:47,375 - INFO - results saved to=query_results.json
2025-05-07 02:41:47,378 - DEBUG - ------finished postprocessing query API
2025-05-07 02:41:47,378 - DEBUG - ----------------------------finished query API----------------------------
2025-05-07 02:41:47,378 - DEBUG - ------finished preprocessing read API
2025-05-07 02:41:47,378 - DEBUG - ------checking constraints for run API
2025-05-07 02:41:47,378 - DEBUG - finding all ttnn files from=ttnn/big_input.ttnn
2025-05-07 02:41:47,378 - DEBUG - checking if file=ttnn/big_input.ttnn exists
2025-05-07 02:41:47,378 - DEBUG - getting file extension of=ttnn/big_input.ttnn
2025-05-07 02:41:47,378 - DEBUG - found file=ttnn/big_input.ttnn
2025-05-07 02:41:47,378 - DEBUG - finding all ttmetal files from=ttnn/big_input.ttnn
2025-05-07 02:41:47,378 - DEBUG - checking if file=ttnn/big_input.ttnn exists
2025-05-07 02:41:47,378 - DEBUG - getting file extension of=ttnn/big_input.ttnn
2025-05-07 02:41:47,378 - DEBUG - ttnn_binary_paths=['ttnn/big_input.ttnn']
2025-05-07 02:41:47,378 - DEBUG - ttmetal_binary_paths=[]
2025-05-07 02:41:47,378 - DEBUG - getting file name of=ttnn/big_input.ttnn
2025-05-07 02:41:47,378 - DEBUG - getting file extension of=ttnn/big_input.ttnn
2025-05-07 02:41:47,387 - DEBUG - ------finished checking constraints for run API
2025-05-07 02:41:47,387 - DEBUG - ------executing run API
2025-05-07 02:41:47,387 - DEBUG - executing ttnn binaries
2025-05-07 02:41:47,387 - DEBUG - setting tt runtime debug env=debug::Env{
        loadKernelsFromDisk: 0
}
2025-05-07 02:41:47,387 - DEBUG - setting tt runtime workaround env=workaround::Env{
        swapBinaryOperands: 1,
        readUpdateIndexFromDeviceForKVCache: 1
        rawHostDataPointerWrapper: 1
}
2025-05-07 02:41:47,387 - DEBUG - setting torch manual seed=0
2025-05-07 02:41:47,387 - DEBUG - opening devices=[0, 1]
Read unexpected run_mailbox value: 0x40 (expected 0x80 or 0x0)
Read unexpected run_mailbox value: 0x40 (expected 0x80 or 0x0)
                 Always |    DEBUG | Device grid size = { 8, 8 }
2025-05-07 02:41:47,524 - INFO - evaluating binary=ttnn/big_input.ttnn
2025-05-07 02:41:47,524 - DEBUG - evaluating program=0 for binary=ttnn/big_input.ttnn
                 Always |  WARNING | Golden information not found
2025-05-07 02:41:47,525 - DEBUG - starting loop=1/1 for binary=ttnn/big_input.ttnn
            RuntimeTTNN |    DEBUG | Starting execution of program: cos
            RuntimeTTNN |    DEBUG | Executing operation: %0 = "ttnn.sin"(%arg0) : (tensor<32x32xf32, #ttnn.ttnn_layout<(d0, d1) -> (d0, d1), <1x1>, memref<1x1x!tt.tile<32x32, f32>, #ttnn.buffer_type<dram>>, <interleaved>>>) -> tensor<32x32xf32, #ttnn.ttnn_layout<(d0, d1) -> (d0, d1), <1x1>, memref<1x1x!tt.tile<32x32, f32>, #ttnn.buffer_type<dram>>, <interleaved>>> loc("/localdev/hkwon/working/single_fb_on_n300/build_simple.py:17:id(1)")
2025-05-07 02:41:48,214 - DEBUG - executing golden comparison
2025-05-07 02:41:48,219 - ERROR - ERROR: test=ttnn/big_input.ttnn experienced an error with exception=TT_FATAL @ /localdev/hkwon/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/tensor/host_buffer/functions.cpp:24: storage.buffers.size() == 1
info:
Can't get a single buffer from multi device host storage, got 2
backtrace:
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libtt_metal.so(+0x53bc4f) [0x7fcfc9dc9c4f]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_ttnn.so(+0x3c43589) [0x7fcfc849e589]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_ttnn.so(+0x3c434e8) [0x7fcfc849e4e8]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_ttnn.so(+0x3c43488) [0x7fcfc849e488]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_ttnn.so(+0x3c43290) [0x7fcfc849e290]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_ttnn.so(+0x3c4316b) [0x7fcfc849e16b]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_ttnn.so(+0x3c0706e) [0x7fcfc846206e]
 --- tt::tt_metal::host_buffer::get_host_buffer(tt::tt_metal::Tensor const&)
 --- tt::stl::Span<float, 18446744073709551615ul> tt::tt_metal::host_buffer::get_as<float>(tt::tt_metal::Tensor&)
 --- std::vector<float, std::allocator<float> > tt::tt_metal::Tensor::to_vector<float>(tt::stl::StrongType<unsigned char, ttnn::QueueIdTag>) const
 --- tt::runtime::ttnn::getTensorDataBuffer(tt::runtime::Tensor)
 --- tt::runtime::getTensorDataBuffer(tt::runtime::Tensor)
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_C.cpython-310-x86_64-linux-gnu.so(+0x2d260) [0x7fd06cef4260]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_C.cpython-310-x86_64-linux-gnu.so(+0x50867) [0x7fd06cf17867]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x18ae12) [0x55f756a53e12]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyObject_MakeTpCall+0x25b) [0x55f756a4a75b]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x198a6b) [0x55f756a61a6b]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyEval_EvalFrameDefault+0x5642) [0x55f756a438b2]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f756a5466c]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyEval_EvalFrameDefault+0x6bf) [0x55f756a3e92f]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x186d18) [0x55f756a4fd18]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0xbd5a4) [0x55f7569865a4]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_C.cpython-310-x86_64-linux-gnu.so(+0x2b0d7) [0x7fd06cef20d7]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x240219) [0x7fcfca5bb219]
 --- tt::runtime::ttnn::ProgramExecutor::runCallback(std::optional<std::function<void (tt::runtime::Binary, tt::runtime::CallbackContext, tt::runtime::OpContext)> >, tt::runtime::Binary&, tt::target::ttnn::Operation const*, tt::runtime::ttnn::ProgramContext*)
 --- tt::runtime::ttnn::ProgramExecutor::execute()
 --- tt::runtime::ttnn::runProgram(std::shared_ptr<tt::tt_metal::distributed::MeshDevice>, tt::runtime::Binary, unsigned int, std::vector<tt::runtime::Tensor, std::allocator<tt::runtime::Tensor> >&)
 --- tt::runtime::ttnn::submit(tt::runtime::Device, tt::runtime::Binary, unsigned int, std::vector<tt::runtime::Tensor, std::allocator<tt::runtime::Tensor> >&)
 --- tt::runtime::submit(tt::runtime::Device, tt::runtime::Binary, unsigned int, std::vector<tt::runtime::Tensor, std::allocator<tt::runtime::Tensor> >&)
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_C.cpython-310-x86_64-linux-gnu.so(+0x27201) [0x7fd06ceee201]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_C.cpython-310-x86_64-linux-gnu.so(+0x3352f) [0x7fd06cefa52f]
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/_C.cpython-310-x86_64-linux-gnu.so(+0x50867) [0x7fd06cf17867]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x18ae12) [0x55f756a53e12]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyObject_MakeTpCall+0x25b) [0x55f756a4a75b]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyEval_EvalFrameDefault+0x5f66) [0x55f756a441d6]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f756a5466c]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyEval_EvalFrameDefault+0x6bf) [0x55f756a3e92f]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f756a5466c]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyEval_EvalFrameDefault+0x804) [0x55f756a3ea74]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyObject_FastCallDictTstate+0xc4) [0x55f756a49934]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyObject_Call_Prepend+0x5c) [0x55f756a5e8ec]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x29cba4) [0x55f756b65ba4]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyObject_MakeTpCall+0x25b) [0x55f756a4a75b]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyEval_EvalFrameDefault+0x59d7) [0x55f756a43c47]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f756a5466c]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyEval_EvalFrameDefault+0x6bf) [0x55f756a3e92f]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x259f56) [0x55f756b22f56]
 --- /opt/ttmlir-toolchain/venv/bin/python(PyEval_EvalCode+0x86) [0x55f756b22e26]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x280808) [0x55f756b49808]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x27b00f) [0x55f756b4400f]
 --- /opt/ttmlir-toolchain/venv/bin/python(+0x2805a5) [0x55f756b495a5]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyRun_SimpleFileObject+0x1a8) [0x55f756b48b88]
 --- /opt/ttmlir-toolchain/venv/bin/python(_PyRun_AnyFileObject+0x47) [0x55f756b48867]
 --- /opt/ttmlir-toolchain/venv/bin/python(Py_RunMain+0x2be) [0x55f756b3ce5e]
 --- /opt/ttmlir-toolchain/venv/bin/python(Py_BytesMain+0x2d) [0x55f756b16e6d]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fd128ce9d90]
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fd128ce9e40]
 --- /opt/ttmlir-toolchain/venv/bin/python(_start+0x25) [0x55f756b16d65]

2025-05-07 02:41:48,226 - DEBUG - finished executing ttnn binaries
2025-05-07 02:41:48,226 - DEBUG - executing ttmetal binaries
2025-05-07 02:41:48,226 - WARNING - no binaries found to run - returning early
2025-05-07 02:41:48,226 - DEBUG - finished executing ttmetal binaries
2025-05-07 02:41:48,226 - DEBUG - ------finished executing run API
2025-05-07 02:41:48,226 - DEBUG - ------postprocessing run API
2025-05-07 02:41:48,226 - ERROR - ERROR: test case=ttnn/big_input.ttnn
2025-05-07 02:41:48,226 - INFO - results saved to=run_results.json
2025-05-07 02:41:48,227 - DEBUG - ------finished postprocessing run API
2025-05-07 02:41:48,227 - DEBUG - ----------------------------finished run API----------------------------
```

### Steps to reproduce the issue

1. Build the TTNN flatbuffer using the Python code below:
```

import torch
from ttmlir.test_utils import compile_to_flatbuffer
from ttmlir.ttir_builder import Operand, TTIRBuilder, Shape
import os

def big_input(shape: Shape):
    def cos(in0: Operand, builder: TTIRBuilder):
        output = builder.cos(in0)
        return output
    dtypes = [torch.float32]
    compile_to_flatbuffer(
        cos, [shape], inputs_types = dtypes, test_base="big_input", system_desc_path = os.environ["SYSTEM_DESC_PATH"], module_dump=True
    )

if __name__ == "__main__":
    input_shape = (32, 32)
    big_input(input_shape)
```
2. Run the flatbuffer with ttrt
`ttrt run ttnn`

### Expected behavior

_No response_

### Please complete the following environment information

This issue occurs starting from commit f2048f42629fca (PR #3174).
Tested with N300 IRD machine

### LINKED ISSUE #3310: runtime/lib/ttnn/utils/utils.cpp:285: storage.num_buffers() == 1
When running builder op tests on n300, all of them fail with:

```
^[[1mLOG_ASSERT @ /localdev/nsmith/src/tt-mlir/runtime/lib/ttnn/utils/utils.cpp:285: storage.num_buffers() == 1      
backtrace:      
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x42e0c4) [0x7f65e51040c4]      
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x42e06d) [0x7f65e510406d]      
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x42e01d) [0x7f65e510401d]      
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x42ddfd) [0x7f65e5103dfd]      
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x42dd18) [0x7f65e5103d18]      
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x42db7b) [0x7f65e5103b7b]      
 --- tt::runtime::ttnn::utils::getRawHostDataPtr(tt::tt_metal::Tensor const&)      
 --- /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime/libTTMLIRRuntime.so(+0x301166) [0x7f65e4fd7166]      
 --- tt::runtime::ttnn::operations::cpu::run(tt::target::ttnn::CpuOp const*, tt::runtime::ttnn::ProgramContext&)      
 --- tt::runtime::ttnn::ProgramExecutor::runOperation(tt::target::ttnn::Operation const*)      
 --- tt::runtime::ttnn::ProgramExecutor::execute()      
 --- tt::runtime::ttnn::runProgram(std::shared_ptr<tt::tt_metal::distributed::MeshDevice>, tt::runtime::Binary, unsigned int, std::vector<tt::runtime::Tensor, std::allocator<tt::runtime::Tensor> >&)      
 --- tt::runtime::ttnn::submit(tt::runtime::Device, tt::runtime::Binary, unsigned int, std::vector<tt::runtime::Tensor, std::allocator<tt::runtime::Tensor> >&)
```

I think this is because ttrt just calls `open_mesh_device` which by default will open a 1x2 grid and default to multi device host storage.  We should populate the mesh shape information into the flatbuffer binary so that for each binary that ttrt runs it can use `create_sub_device_mesh` with the correct underlying mesh shape.

Repro on an n300:
```bash
pytest -v test/python/golden/test_ttir_ops.py --sys-desc=${SYSTEM_DESC_PATH}
ttrt run ttnn
```

### PR DESCRIPTION
**Pull request by ctodTT**
### Ticket
Closes #3238
Closes #3310

### Problem description
Flatbuffers that expect to be run on a unidevice system fail to run on multidevice systems.

### What's changed
An expected mesh shape is now encoded into every flatbuffer generated, and then read by `ttrt`. `ttrt` then opens a mesh device of the correct size if the system topology does not match.

### CODE REVIEW

File: lib/Dialect/TT/IR/TTOpsTypes.cpp [hunk 1]
```diff
@@ -1213,6 +1213,12 @@ DeviceAttr DeviceAttr::get(::mlir::MLIRContext *context,
                            SystemDescAttr systemDesc,
                            ArrayRef<int64_t> meshShape) {
   int64_t numChips = ttmlir::utils::volume(meshShape);
+  fprintf(stderr, "desc numChips: %lu\n", systemDesc.getChipDescs().size());
+  fprintf(stderr, "meshShape: [");
+  for (size_t i = 0; i < meshShape.size(); i++) {
+    fprintf(stderr, "%lu, ", meshShape[i]);
+  }
+  fprintf(stderr, "]\n");
```
Comment (nsmithtt) [inline lib/Dialect/TT/IR/TTOpsTypes.cpp]: Stray prints.

File: include/ttmlir/Target/TTNN/program.fbs [hunk 2]
```diff
@@ -93,4 +93,5 @@ table Program {
   debug_info: DebugInfo;
   // Flag to indicate if this program is intended to be called or only for internal use (e.g. hoisted const-eval func).
   private: bool;
+  mesh_shape: Dim2d;
```
Comment (nsmithtt) [inline include/ttmlir/Target/TTNN/program.fbs:98]: Can you also add it to the metal flatbuffer, whichever table makes most sense in `include/ttmlir/Target/TTMetal/binary.fbs`.

File: lib/Target/TTNN/TTNNToFlatbuffer.cpp [hunk 3]
```diff
@@ -2170,9 +2170,25 @@ std::shared_ptr<void> ttnnToFlatbuffer(
...
+
+    ArrayRef<int64_t> meshShapeArr = deviceAttr.getMeshShape();
+
+    // Default to 1x1 if not specified.
+    if (meshShapeArr.empty()) {
+      meshShape = ::tt::target::Dim2d(1, 1);
+    } else {
+      assert(meshShapeArr.size() == 2 && "Ill-Sized Mesh Shape");
+      meshShape = ::tt::target::Dim2d(meshShapeArr[0], meshShapeArr[1]);
+    }
```
Comment (nsmithtt) [inline lib/Target/TTNN/TTNNToFlatbuffer.cpp]: Maybe let's make a little helper func `inline Dim2d deviceMeshToFlatbuffer(DeviceAttr deviceAttr)` since the code is used in multiple places (and will also be needed for ttmetal flatbuffer).  We can put this in `include/ttmlir/Target/Utils/MLIRToFlatbuffer.h`.

File: test/python/golden/conftest.py [hunk 4]
```diff
@@ -23,6 +23,7 @@ def pytest_addoption(parser):
     parser.addoption(
         "--allow-subset-mesh",
         action="store_true",
+        default=True,
```
Comment (nsmithtt) [inline test/python/golden/conftest.py]: I think we don't want this to be defaulted to true, or maybe there's a way for CI to toggle this.  But in CI we want to _only_ run tests that match the respective mesh shape.  Thinking about it just now, that maybe there should be an exception for n300, I'm worried now are single chip tests running?

File: runtime/tools/ttrt/ttrt/common/run.py [hunk 5]
```diff
@@ -523,14 +525,29 @@ def convert_input_layouts(device, inputs, fbb, program_index):
...
-            device = ttrt.runtime.open_mesh_device(mesh_shape, mesh_options)
+
+            device_open = False
 
             for bin in binaries:
+
                 try:
+
+                    fb_mesh_shape = bin.get_program(0).mesh_shape()
+                    num_mesh_devices = reduce(operator.mul, fb_mesh_shape, 1)
```
Comment (tapspatel) [inline runtime/tools/ttrt/ttrt/common/run.py:575]: can you add a comment here explaining we open the device in 1x"n" and then reshape depending on the mesh in the flatbuffer.

File: test/python/golden/test_ttir_ops.py [hunk 6]
```diff
@@ -888,6 +888,9 @@ def ones(builder: TTIRBuilder, unit_attrs: List[str] = None):
     )
 
 
+# Empty will intermittently fail golden checks during many flatbuffer
```
Comment (tapspatel) [inline test/python/golden/test_ttir_ops.py:949]: why is this failing?

Comment (ctodTT) [reply test/python/golden/test_ttir_ops.py:949]: It fails because empty creates a tensor with uninitialized data, which when run in directory mode for some reason mismatches with the program level golden. I am not sure why my changes unveiled this bug, but I don't believe that is directly caused by my changes. I should make an issue for this and link it in this comment

File: runtime/tools/ttrt/ttrt/common/run.py (hunk 5 above)
Comment (ctodTT) [reply runtime/tools/ttrt/ttrt/common/run.py:575]: That's not exactly correct, this opens a mesh of the shape provided by the flatbuffer, given that the flatbuffer supplied mesh shape doesn't exceed the number of devices present. I added a comment explaining that though!

File: test/python/golden/test_ttir_ops.py (hunk 6 above)
Comment (tapspatel) [reply test/python/golden/test_ttir_ops.py:949]: ok, we should start tagging failing pytests with issues and follow-up with them.

Comment (ctodTT) [reply test/python/golden/test_ttir_ops.py:949]: Agreed

File: runtime/tools/ttrt/ttrt/common/run.py [hunk 7]
```diff
@@ -1006,13 +1022,16 @@ def convert_input_layouts(device, inputs, fbb, program_index):
...
 
                     if self["--emitc"]:
                         ttrt.runtime.test.close_so(emitc_dylib_handle)
 
-            ttrt.runtime.unregister_hooks()
-            ttrt.runtime.close_mesh_device(device)
+                    ttrt.runtime.unregister_hooks()
+
+                    # Only close the device it if was opened
+                    if device_open:
```
Comment (nsmithtt) [inline runtime/tools/ttrt/ttrt/common/run.py]: Under what circumstances is the device not open?  Can we just check the device against None?

File: include/ttmlir/Target/Utils/MLIRToFlatbuffer.h [hunk 8]
```diff
@@ -39,6 +39,29 @@ struct GoldenTensor {
...
 
+/**
+ * Given a `DeviceAttr`, returns a flatbuffer representation (i.e. a `Dim2d`) of
+ * the mesh shape of the device.
+ *
+ * If no mesh shape is specified (i.e. the mesh
+ * shape is an empty array), then the default value of 1x1 will be returned.
+ */
+inline ::tt::target::Dim2d deviceToFlatbufferMeshShape(const DeviceAttr attr) {
+
```
Comment (nsmithtt) [inline include/ttmlir/Target/Utils/MLIRToFlatbuffer.h]: nit: newline

File: lib/Target/TTMetal/TTMetalToFlatbuffer.cpp [hunk 9]
```diff
@@ -675,9 +675,14 @@ static std::shared_ptr<void> translateModuleToFlatbuffer(
     flatbuffers::Offset<target::DebugInfo> debugInfo =
         debugInfoToFlatbuffer(fbb, "ttmetal", module, goldenMap, moduleCache);
 
+    DeviceAttr deviceAttr = lookupDevice(entry);
+    assert(deviceAttr);
```
Comment (nsmithtt) [inline lib/Target/TTMetal/TTMetalToFlatbuffer.cpp]: Nit: It's probably enough to just have the assert inside of `deviceToFlatbufferMeshShape`

File: lib/Target/TTNN/TTNNToFlatbuffer.cpp [hunk 10]
```diff
@@ -2170,9 +2170,15 @@ std::shared_ptr<void> ttnnToFlatbuffer(
         funcOpToProgram<::tt::target::ttnn::Operation>(
             cache, func, emitTTNNOperation, tensorValueToFlatbuffer,
             programIdxMap);
+
+    DeviceAttr deviceAttr = lookupDevice(func);
+    assert(deviceAttr);
```
Comment (nsmithtt) [inline lib/Target/TTNN/TTNNToFlatbuffer.cpp]: Nit: It's probably enough to just have the assert inside of `deviceToFlatbufferMeshShape`

File: runtime/tools/ttrt/ttrt/common/run.py (hunk 7 above)
Comment (ctodTT) [reply runtime/tools/ttrt/ttrt/common/run.py]: Technically, it's possible that opening the device fails within the `try:` and `device` is left unbound. Since this is in the `finally:` block, in that case there will be no bound variable `device` to close. I can refactor it to have `device` set to `None` outside the loop, and reset it to that within the `finally` block here, but I thought this to be more expressive.

Comment (nsmithtt) [reply runtime/tools/ttrt/ttrt/common/run.py]: I'd kinda prefer just a single variable, esp if the state that it's tracking is 1-1 to the state of the device.

**Review by phizalev-TT — APPROVED** [review]
