### PR TITLE
Fix argmax for boolean inputs

### LINKED ISSUE #2387: StableHLO reduce inside argmax fails to compile
The following graph is emitted from a test in tt-xla:
```mlir
module @jit___call__ attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func private @argmax(%arg0: tensor<2x7xi1>) -> tensor<2xi32> {
    %c = stablehlo.constant dense<0> : tensor<i32>
    %c_0 = stablehlo.constant dense<false> : tensor<i1>
    %0 = stablehlo.iota dim = 1 : tensor<2x7xi32>
    %1:2 = stablehlo.reduce(%arg0 init: %c_0), (%0 init: %c) across dimensions = [1] : (tensor<2x7xi1>, tensor<2x7xi32>, tensor<i1>, tensor<i32>) -> (tensor<2xi1>, tensor<2xi32>)
     reducer(%arg1: tensor<i1>, %arg3: tensor<i1>) (%arg2: tensor<i32>, %arg4: tensor<i32>)  {
      %2 = stablehlo.compare  GT, %arg1, %arg3,  UNSIGNED : (tensor<i1>, tensor<i1>) -> tensor<i1>
      %3 = stablehlo.compare  NE, %arg1, %arg1,  UNSIGNED : (tensor<i1>, tensor<i1>) -> tensor<i1>
      %4 = stablehlo.or %2, %3 : tensor<i1>
      %5 = stablehlo.compare  EQ, %arg1, %arg3,  UNSIGNED : (tensor<i1>, tensor<i1>) -> tensor<i1>
      %6 = stablehlo.compare  LT, %arg2, %arg4,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1>
      %7 = stablehlo.and %5, %6 : tensor<i1>
      %8 = stablehlo.or %4, %7 : tensor<i1>
      %9 = stablehlo.select %4, %arg1, %arg3 : tensor<i1>, tensor<i1>
      %10 = stablehlo.select %8, %arg2, %arg4 : tensor<i1>, tensor<i32>
      stablehlo.return %9, %10 : tensor<i1>, tensor<i32>
    }
    return %1#1 : tensor<2xi32>
  }
}
```

### PR DESCRIPTION
**Pull request by sgligorijevicTT**
### Ticket
Fixes #2387 

### Problem description
ReduceOp conversion pattern fails to match the ReduceOp emitted from JAX for argmax over boolean inputs.

### What's changed
I added the case for i1(booleans) inside the `checkInitValue` function.

### Checklist
- [X] New/Existing tests provide coverage for changes

### CODE REVIEW

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 1]
```diff
@@ -493,6 +496,11 @@ class StableHLOToTTIRReduceOpConversionPattern
       if (*initValueOp.getValue().value_begin<int64_t>() != desiredI64) {
         return false;
       }
+    } else if (initValueOp.getResult().getType().getElementType().isInteger(
+                   1)) {
+      if (*initValueOp.getValue().value_begin<bool>() != desiredI1) {
+        return false;
```
Comment (azecevicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:502]: I know you just continued existing pattern, but can you change all cases from
```cpp
if (cond) {
  return false;
}
```
to 
```cpp
return !cond;
```
as they are mutually exclusive, so we will always hit at most one case.

**Review by azecevicTT — APPROVED** [review]

**Review by mrakitaTT — APPROVED** [review]

**Review by mmanzoorTT — APPROVED** [review]

**Review by wooseokTT — APPROVED** [review]
