### PR TITLE
Adding bf16 data type workaround for max_pool2d op and fixing embedding workaround tests

### LINKED ISSUE #1389: Handle max_pool2d input dataformat float32
When I run resnet test from forge I get unexpeted error: 

`loc("max_pool2d_17"("forward":4294967295:3591)): error: 'ttnn.max_pool2d' op ttnn.max_pool2d currently only supports an input type of bfloat16. Recieved 'f32'.`

Turns out it is due to assert in verify ` mlir::tt::ttnn::Conv2dOp::verify()` added in [PR](https://github.com/tenstorrent/tt-mlir/commit/5fd26305487fd4b28eabd3f5de826f35d65b09d0#diff-a6cb8b5b9ca05403b2ffed57b2fc9e353ac983c5f7ae34c7a1cb385e7af2777fR93).

So If ttnn.max_pool2d only supports bfloat16 we shouldn't just fail compile if its input is float32. We should probably add a cast op to handle this and move on with compile. 
 
@sdjordjevicTT can we prioritize this because it is a blocker for ResNet bringup?
fyi @nvukobratTT

### PR DESCRIPTION
**Pull request by sdjordjevicTT**
Applying bf16 data type workaround on max_pool2d op.

With this change, I rewrote the workaround test, silicon, and compiler test.

Closes #1389

### CODE REVIEW

File: runtime/lib/ttnn/operations/layout/typecast.cpp [hunk 1]
```diff
@@ -6,6 +6,7 @@
 #include "tt/runtime/detail/ttnn.h"
 #include "tt/runtime/ttnn/operations/utils.h"
 #include "tt/runtime/ttnn/utils.h"
+#include <ttnn/operations/core/core.hpp>
```
Comment (jnie-TT) [inline runtime/lib/ttnn/operations/layout/typecast.cpp:9]: nit: quotation marks `#include "ttnn/operations/core/core.hpp"`

**Comment by sdjordjevicTT** [comment]
Created the following issue to track the runtime workaround:
https://github.com/tenstorrent/tt-mlir/issues/1658

File: runtime/include/tt/runtime/detail/workarounds.h [hunk 2]
```diff
@@ -39,13 +40,19 @@ struct Env {
...
 
+  // TODO(bug #1658): We're currently use ttnn::to_dtype operation to cast the
+  // data type of a tensor on host. Once we have improved the typecast operation
+  // to handle this, we should remove this workaround.
+  bool typecastOnHost;
+
 private:
   constexpr Env(bool maxpool2dPreshard, bool swapBinaryOperands,
-                bool readUpdateIndexFromDeviceForKVCache)
+                bool readUpdateIndexFromDeviceForKVCache, bool typecastOnHost)
```
Comment (jnie-TT) [inline runtime/include/tt/runtime/detail/workarounds.h:50]: Maybe name this as toDtypeOnHost or something so that it's explicit that we're using to_dtype when typcasting on host.

Also please add a ttrt command line option to toggle this in `runtime/tools/python/ttrt/common/run.py`, the procedure will be the same as the other workaround flags.

Comment (sdjordjevicTT) [reply runtime/include/tt/runtime/detail/workarounds.h]: Renamed typecastOnHost to toDtypeOnHost. I added an option in run.py; please double-check if I implemented it correctly.

**Review by jnie-TT — APPROVED** [review]
Runtime changes look good, thanks Stefan!

**Review by mtopalovicTT — APPROVED** [review]

File: lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp [hunk 3]
```diff
@@ -7,6 +7,7 @@
 #include "ttmlir/Utils.h"
 
 #include "llvm/ADT/SmallVector.h"
+#include <optional>
```
Comment (jserbedzijaTT) [inline lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp:10]: Is this needed?

**Review by jserbedzijaTT — APPROVED** [review]
Looks good!

**Review by tapspatel — APPROVED** [review]

File: lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp (hunk 3 above)
Comment (sdjordjevicTT) [reply lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp]: You are right, this was added by accident :) Removing it...
