### PR TITLE
Hoist constant op in TTNN

### LINKED ISSUE #3180: Constant op is not marked with TTCreationOpTrait
### Describe the bug

Mark constant op as creation op in TTNN. It's already marked as creation in TTIR through TTIR_CreationOp base class. See if we can derive same base class in TTNN and make all creation ops inherit from it.

### Steps to reproduce the issue

_No response_

### Expected behavior

_No response_

### Please complete the following environment information

_No response_

### PR DESCRIPTION
**Pull request by mtopalovicTT**
* Previously constant op in TTNN was not tagged with CreationOp trait. This PR adds tag for constant op and reconstructs creation ops in TTNN to have similar strucutre to TTIR equivalents.
* Fixed bug when return op was pulled in for hoisting. This can happen if whole graph can be const evaled.
* Removed constant for commuting conv2d and multiply to function arguments only.
* Added test for both commuting creation ops in conv2d+multiply commute and const evaling creation ops.

closes #3180

### CODE REVIEW

**Comment by mtopalovicTT** [comment]
FYI @vwellsTT

File: lib/Dialect/TTIR/Transforms/TTIRFusing.cpp [hunk 1]
```diff
@@ -294,13 +294,14 @@ class Conv2dWithMultiply : public mlir::OpRewritePattern<MultiplyOp> {
...
-    auto isConstant = [&constParams](mlir::Value value) {
+    auto isConstant = [&constParams, conv2dOp](mlir::Value value) {
       if (auto blockArg = mlir::dyn_cast<BlockArgument>(value)) {
         return constParams.contains(blockArg);
       }
 
-      // TODO(milant): Check for TT_CreationOpTrait after issue #3180 lands.
-      return false;
+      Operation *op = value.getDefiningOp();
+      return op->hasTrait<mlir::tt::Trait::TTCreationOpTrait>() &&
```
Comment (azecevicTT) [inline lib/Dialect/TTIR/Transforms/TTIRFusing.cpp:303]: This isn't entirely true. I think this https://mlir.llvm.org/doxygen/classmlir_1_1OpTrait_1_1ConstantLike.html#details is exactly what we need. If you look at the definition, it says: _These are non-side effecting operations with one result and zero operands that can always be folded to a specific attribute value._
While all creation ops satisfy _non-side effecting operations with one result and zero operands_, the part _can always be folded to a specific attribute value_ is not true for `empty` and `construct_tensor`. They are by definition ND.
On the other hand you can make an argument that doing an operation on a (non side-effecting) ND valued tesnor results in UB, so it's a free game for the optimizations like this, because the end result is going to be UB in both cases (if we ignore potential exceptions for the moment).

File: include/ttmlir/Dialect/TTIR/IR/TTIROps.td [hunk 2]
```diff
@@ -1991,13 +1991,13 @@ def TTIR_ArangeOp : TTIR_CreationOp<"arange"> {
     Produces a tensor with values from `start` to `end` (exclusive) with a step size of `step`, along the dimension specified by `arange_dimension`.
 
     Examples:
-      %0 = "ttir.arange"() {start = 0 : i64, end = 5 : i64 step = 1 : i64, arange_dimension = 0 : i64} : () -> tensor<5xi64>
+      %0 = "ttir.arange"() {start = 0 : si64, end = 5 : si64 step = 1 : i64, arange_dimension = 0 : i64} : () -> tensor<5xi64>
```
Comment (azecevicTT) [inline include/ttmlir/Dialect/TTIR/IR/TTIROps.td:1994]: Good catch!

**Review by azecevicTT — APPROVED** [review]

File: lib/Dialect/TTIR/Transforms/TTIRFusing.cpp (hunk 1 above)
Comment (vwellsTT) [reply lib/Dialect/TTIR/Transforms/TTIRFusing.cpp:303]: Hmm, yeah I think in terms of const-eval `empty` and `construct_tensor` need to be treated the same as other creationOps.

> While all creation ops satisfy non-side effecting operations with one result and zero operands, the part can always be folded to a specific attribute value is not true for empty and construct_tensor. They are by definition ND.

Truthfully, I'm not sure I understand this; what makes `empty` different from `zeros` say in this regard?  ND = N-dimensional?

File: lib/Transforms/ConstEvalHoist.cpp [hunk 3]
```diff
@@ -159,6 +159,11 @@ class ConstEvalAnalyze {
   }
 
   void processOp(Operation *op) {
+    // Skip terminator ops.
```
Comment (vwellsTT) [inline lib/Transforms/ConstEvalHoist.cpp:162]: Good catch! I guess I should have a testcase for "entire func is const-eval'ed" case you mention (but I'm happy to add this myself in a follow-on)

**Review by vwellsTT — APPROVED** [review]
Thanks for catching const-eval issues! :)

File: lib/Dialect/TTIR/Transforms/TTIRFusing.cpp (hunk 1 above)
Comment (mtopalovicTT) [reply lib/Dialect/TTIR/Transforms/TTIRFusing.cpp:303]: ND - non deterministic. With empty you just get empty tensor which is filled with random values.

File: lib/Transforms/ConstEvalHoist.cpp (hunk 3 above)
Comment (mtopalovicTT) [reply lib/Transforms/ConstEvalHoist.cpp:162]: Ive added this in ttnn const-eval.mlir, last test case has all creation ops as operands, so no need. Do you want me to add more tests?

File: lib/Dialect/TTIR/Transforms/TTIRFusing.cpp (hunk 1 above)
Comment (vwellsTT) [reply lib/Dialect/TTIR/Transforms/TTIRFusing.cpp:303]: Oh, I see.  Makes more sense, thanks.
I'm not sure I see any case where optimizing `empty` as if it was a `constant` is problematic for us, so maybe it's fine to just use `ConstantLike`.  But no strong opinion either way, I think having our own attr isn't particularly problematic imo too.

File: lib/Transforms/ConstEvalHoist.cpp (hunk 3 above)
Comment (vwellsTT) [reply lib/Transforms/ConstEvalHoist.cpp:162]: Ah, I was thinking something like:
```
  func.func @forward_all_const(%arg0: tensor<32x32xbf16> {tt.argument_type = #tt.argument_type<constant>}, %arg1: tensor<32x32xbf16> {tt.argument_type = #tt.argument_type<constant>}) -> tensor<32x32xbf16> {
    // CHECK: tt.load_cached(@forward_const_eval_0, [%arg2, %arg3])
    %0 = ttir.empty() : tensor<32x32xbf16>
    // CHECK: "ttnn.add"(%arg0, %arg1)
    %1 = "ttir.add"(%arg0, %arg1, %0) : (tensor<32x32xbf16>, tensor<32x32xbf16>, tensor<32x32xbf16>) -> tensor<32x32xbf16>
    return %1 : tensor<32x32xbf16>
  }
  ```
  but yeah I think your testcase covers this logic anyway, nvm

Comment (mtopalovicTT) [reply lib/Transforms/ConstEvalHoist.cpp:162]: Sure i will add that

**Review by nsmithtt — APPROVED** [review]
