### PR TITLE
Handle stableHLO 64 bit floating point type

### LINKED ISSUE #1206: stablehlo::ConstantOp - ElementsAttr does not provide iteration facilities for type `int`, see attribute: dense<true> : tensor<i1>
Example graph:
```
module {
  func.func @main(%arg0: tensor<1x12x12x12xf32>) -> tensor<1x12x12x12xf32> {
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f64>
    %cst_0 = stablehlo.constant dense<0xFF800000> : tensor<f32>
    %cst_1 = stablehlo.constant dense<0.000000e+00> : tensor<f32>
    %c = stablehlo.constant dense<true> : tensor<i1>
    %cst_2 = arith.constant dense<0xFFF0000000000000> : tensor<1xf64>
    %0 = stablehlo.reduce(%arg0 init: %cst_0) applies stablehlo.maximum across dimensions = [3] : (tensor<1x12x12x12xf32>, tensor<f32>) -> tensor<1x12x12xf32>
    %1 = stablehlo.reshape %0 : (tensor<1x12x12xf32>) -> tensor<1x12x12x1xf32>
    %2 = stablehlo.broadcast_in_dim %arg0, dims = [0, 1, 2, 3] : (tensor<1x12x12x12xf32>) -> tensor<1x12x12x12xf32>
    %3 = stablehlo.broadcast_in_dim %1, dims = [0, 1, 2, 3] : (tensor<1x12x12x1xf32>) -> tensor<1x12x12x12xf32>
    %4 = stablehlo.subtract %2, %3 : tensor<1x12x12x12xf32>
    %5 = stablehlo.exponential %4 : tensor<1x12x12x12xf32>
    %6 = stablehlo.reduce(%5 init: %cst_1) applies stablehlo.add across dimensions = [3] : (tensor<1x12x12x12xf32>, tensor<f32>) -> tensor<1x12x12xf32>
    %7 = stablehlo.reshape %6 : (tensor<1x12x12xf32>) -> tensor<1x12x12x1xf32>
    %8 = stablehlo.broadcast_in_dim %5, dims = [0, 1, 2, 3] : (tensor<1x12x12x12xf32>) -> tensor<1x12x12x12xf32>
    %9 = stablehlo.broadcast_in_dim %7, dims = [0, 1, 2, 3] : (tensor<1x12x12x1xf32>) -> tensor<1x12x12x12xf32>
    %10 = stablehlo.divide %8, %9 : tensor<1x12x12x12xf32>
    %11 = stablehlo.convert %cst_2 : tensor<1xf64>
    %12 = stablehlo.reshape %11 : (tensor<1xf64>) -> tensor<f64>
    %13 = stablehlo.convert %12 : (tensor<f64>) -> tensor<f32>
    %14 = stablehlo.broadcast_in_dim %13, dims = [] : (tensor<f32>) -> tensor<1x12x12x12xf32>
    %15 = stablehlo.compare  EQ, %2, %14,  FLOAT : (tensor<1x12x12x12xf32>, tensor<1x12x12x12xf32>) -> tensor<1x12x12x12xi1>
    %16 = stablehlo.reduce(%15 init: %c) applies stablehlo.and across dimensions = [3] : (tensor<1x12x12x12xi1>, tensor<i1>) -> tensor<1x12x12xi1>
    %17 = stablehlo.reshape %16 : (tensor<1x12x12xi1>) -> tensor<1x12x12x1xi1>
    %18 = stablehlo.convert %cst : (tensor<f64>) -> tensor<f32>
    %19 = stablehlo.broadcast_in_dim %17, dims = [0, 1, 2, 3] : (tensor<1x12x12x1xi1>) -> tensor<1x12x12x12xi1>
    %20 = stablehlo.broadcast_in_dim %18, dims = [] : (tensor<f32>) -> tensor<1x12x12x12xf32>
    %21 = stablehlo.broadcast_in_dim %10, dims = [0, 1, 2, 3] : (tensor<1x12x12x12xf32>) -> tensor<1x12x12x12xf32>
    %22 = stablehlo.select %19, %20, %21 : tensor<1x12x12x12xi1>, tensor<1x12x12x12xf32>
    return %22 : tensor<1x12x12x12xf32>
  }
}
```

Trace dump:
```
ElementsAttr does not provide iteration facilities for type `int`, see attribute: dense<true> : tensor<i1>
invalid `T` for ElementsAttr::getValues
UNREACHABLE executed at /opt/ttmlir-toolchain/include/mlir/IR/BuiltinAttributeInterfaces.h:306!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.        Program arguments: ttmlir-opt --stablehlo-to-ttir-pipeline=enable-remove-dead-values=true results/mlir_tests/stable_hlo/aten::_safe_softmax_0.mlir
 #0 0x00007f81f1bd907b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/ttmlir-toolchain//lib/libLLVM.so.20.0git+0x11df07b)
 #1 0x00007f81f1bd71c8 llvm::sys::RunSignalHandlers() (/opt/ttmlir-toolchain//lib/libLLVM.so.20.0git+0x11dd1c8)
 #2 0x00007f81f1bd83a9 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f81f04d2520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f81f05269fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x00007f81f05269fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x00007f81f05269fc pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x00007f81f04d2476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007f81f04b87f3 abort ./stdlib/abort.c:81:7
 #9 0x00007f81f1b5c5e3 llvm::install_fatal_error_handler(void (*)(void*, char const*, bool), void*) (/opt/ttmlir-toolchain//lib/libLLVM.so.20.0git+0x11625e3)
#10 0x00005640e24ce2e3 (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x17542e3)
#11 0x00005640e2557d57 (anonymous namespace)::StableHLOToTTIRConstantOpConversionPattern::matchAndRewrite(mlir::stablehlo::ConstantOp, mlir::stablehlo::ConstantOpAdaptor, mlir::ConversionPatternRewriter&) const StableHLOToTTIRPatterns.cpp:0:0
#12 0x00005640e25579bd mlir::OpConversionPattern<mlir::stablehlo::ConstantOp>::matchAndRewrite(mlir::Operation*, llvm::ArrayRef<mlir::Value>, mlir::ConversionPatternRewriter&) const (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x17dd9bd)
#13 0x00005640e2c58613 mlir::ConversionPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1ede613)
#14 0x00005640e2c7b832 void llvm::function_ref<void ()>::callback_fn<mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>)::'lambda'()>(long) PatternApplicator.cpp:0:0
#15 0x00005640e2c7ad3e mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1f00d3e)
#16 0x00005640e2c56c8d (anonymous namespace)::OperationLegalizer::legalize(mlir::Operation*, mlir::ConversionPatternRewriter&) DialectConversion.cpp:0:0
#17 0x00005640e2c58f7c mlir::OperationConverter::convert(mlir::ConversionPatternRewriter&, mlir::Operation*) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1edef7c)
#18 0x00005640e2c5cbae mlir::OperationConverter::convertOperations(llvm::ArrayRef<mlir::Operation*>) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1ee2bae)
#19 0x00005640e2c5d494 mlir::applyFullConversion(llvm::ArrayRef<mlir::Operation*>, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1ee3494)
#20 0x00005640e2c5d513 mlir::applyFullConversion(mlir::Operation*, mlir::ConversionTarget const&, mlir::FrozenRewritePatternSet const&, mlir::ConversionConfig) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1ee3513)
#21 0x00005640e254733f (anonymous namespace)::ConvertStableHLOToTTIRPass::runOnOperation() StableHLOToTTIRPass.cpp:0:0
#22 0x00005640e2d641d0 void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::'lambda0'()>(long) Pass.cpp:0:0
#23 0x00005640e2d62704 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1fe8704)
#24 0x00005640e2d6288a mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1fe888a)
#25 0x00005640e2d629e5 mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1fe89e5)
#26 0x00005640e2d62cde mlir::PassManager::run(mlir::Operation*) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1fe8cde)
#27 0x00005640e1f2c16c performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#28 0x00005640e1f2c647 processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, llvm::ThreadPoolInterface*) MlirOptMain.cpp:0:0
#29 0x00005640e1f2c72c llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#30 0x00005640e2e6a145 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x20f0145)
#31 0x00005640e1f29334 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x11af334)
#32 0x00005640e1f2c946 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x11b2946)
#33 0x00005640e1f2cad9 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x11b2ad9)
#34 0x00005640e103725f main (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x2bd25f)
#35 0x00007f81f04b9d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#36 0x00007f81f04b9e40 call_init ./csu/../csu/libc-start.c:128:20
#37 0x00007f81f04b9e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#38 0x00005640e1037145 _start (/localdev/aknezevic/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x2bd145)
```

### LINKED ISSUE #1285: [StableHLO] 64 bit floating point types
TTNN does not support 64 bit floating point types. Convert them to 32 bit type to avoid any crash.

Error message
```
ttmlir-opt: /localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir/include/ttmlir/Dialect/TT/IR/TTOpsTypes.h:97: DataType mlir::tt::elementTypeToDataType(Type): Assertion `false && "unsupported float type"' failed.
```

Trace dump
```
ttmlir-opt: /localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir/include/ttmlir/Dialect/TT/IR/TTOpsTypes.h:97: DataType mlir::tt::elementTypeToDataType(Type): Assertion `false && "unsupported float type"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ttmlir-opt --ttir-to-ttnn-backend-pipeline results/mlir_tests/ttir/aten::add.Tensor_27.mlir
 #0 0x00007f880f8b70d5 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/ttmlir-toolchain//lib/libLLVM.so.20.0git+0xe550d5)
 #1 0x00007f880f8b74f7 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f880e53a520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007f880e58e9fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #4 0x00007f880e58e9fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #5 0x00007f880e58e9fc pthread_kill ./nptl/pthread_kill.c:89:10
 #6 0x00007f880e53a476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #7 0x00007f880e5207f3 abort ./stdlib/abort.c:81:7
 #8 0x00007f880e52071b _nl_load_domain ./intl/loadmsgcat.c:1177:9
 #9 0x00007f880e531e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#10 0x000055b5835cdadf mlir::tt::elementTypeToDataType(mlir::Type) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x128dadf)
#11 0x000055b5835cd84a mlir::tt::TileType::get(mlir::MLIRContext*, mlir::Type, llvm::ArrayRef<long>) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x128d84a)
#12 0x000055b583755035 mlir::tt::ttir::createToLayoutOp(mlir::PatternRewriter&, mlir::Location, mlir::Value, mlir::tt::MemorySpace, mlir::tt::TensorMemoryLayout, bool) Layout.cpp:0:0
#13 0x000055b5837544c9 mlir::tt::ttir::TTIRLayoutDPSOperandsRewriter::matchAndRewrite(mlir::DestinationStyleOpInterface, mlir::PatternRewriter&) const (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x14144c9)
#14 0x000055b582ec7a2a mlir::detail::OpOrInterfaceRewritePatternBase<mlir::DestinationStyleOpInterface>::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0xb87a2a)
#15 0x000055b583f89bff void llvm::function_ref<void ()>::callback_fn<mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>)::$_2>(long) PatternApplicator.cpp:0:0
#16 0x000055b583f876c6 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<llvm::LogicalResult (mlir::Pattern const&)>) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1c476c6)
#17 0x000055b583f6ebff (anonymous namespace)::GreedyPatternRewriteDriver::processWorklist() GreedyPatternRewriteDriver.cpp:0:0
#18 0x000055b583f6e241 void llvm::function_ref<void ()>::callback_fn<(anonymous namespace)::RegionPatternRewriteDriver::simplify(bool*) &&::$_8>(long) GreedyPatternRewriteDriver.cpp:0:0
#19 0x000055b583f6cb37 mlir::applyPatternsAndFoldGreedily(mlir::Region&, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig, bool*) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1c2cb37)
#20 0x000055b5837507e4 mlir::tt::ttir::TTIRLayout::runOnOperation() (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x14107e4)
#21 0x000055b5840508a2 void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_7>(long) Pass.cpp:0:0
#22 0x000055b58404ce23 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1d0ce23)
#23 0x000055b58404d22b mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1d0d22b)
#24 0x000055b58404eb43 mlir::PassManager::run(mlir::Operation*) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1d0eb43)
#25 0x000055b58327a5cd performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#26 0x000055b58327a287 llvm::LogicalResult llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::$_3>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#27 0x000055b584162459 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<llvm::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, llvm::StringRef, llvm::StringRef) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x1e22459)
#28 0x000055b58327697b mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0xf3697b)
#29 0x000055b583276bb4 mlir::MlirOptMain(int, char**, llvm::StringRef, llvm::StringRef, mlir::DialectRegistry&) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0xf36bb4)
#30 0x000055b583276e28 mlir::MlirOptMain(int, char**, llvm::StringRef, mlir::DialectRegistry&) (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0xf36e28)
#31 0x000055b58259e2ef main (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x25e2ef)
#32 0x00007f880e521d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#33 0x00007f880e521e40 call_init ./csu/../csu/libc-start.c:128:20
#34 0x00007f880e521e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#35 0x000055b58259e1d5 _start (/localdev/mmanzoor/compiler/tt-torch/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt+0x25e1d5)
```

Simplified stablehlo graph
```
  func.func public @test_f64_splat() -> tensor<64xf64> {
    %0 = stablehlo.constant dense<0.3> : tensor<64xf64>
    return %0 : tensor<64xf64>
  }
```

### PR DESCRIPTION
**Pull request by mmanzoorTT**
Fixes #1206 
Fixes #1285

### CODE REVIEW

**Review by LPanosTT — APPROVED** [review]

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp [hunk 1]
```diff
@@ -43,18 +44,29 @@ class StablehloTypeConverter : public TypeConverter {
...
+        // Convert 64 bit integer element type to 32 bit integer.
+        if (isa<IntegerType>(type.getElementType())) {
+          elementType = IntegerType::get(context, 32);
+          changed = true;
+        }
+        // Convert 64 bit float element type to 32 bit float.
+        else if (isa<FloatType>(type.getElementType())) {
+          elementType = FloatType::getF32(context);
+          changed = true;
+        }
```
Comment (nsmithtt) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp:69]: This relates to another issue recently filed, I think we want this kind of data format conversion to happen in TTIR.  It's probably sufficient to land this PR as is since there's already a lot of this kind of handling in stablehlo conversion, but at some point we need to make a concerted effort to migrate it to TTIR.

https://github.com/tenstorrent/tt-mlir/issues/1277#issuecomment-2478587644

fyi @mrakitaTT, @AleksKnezevic

Comment (mmanzoorTT) [reply lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp:69]: I agree with you. We need a dedicated TTIR->TTIR pass to handle all the data types issues in one place ultimately. I was planning to work on it but didn't get a chance. We are only missing support for `f64` in stableHLO->TTIR for current tt-torch models. so this is a quick fix till we have a dedicated pass.

**Review by nsmithtt — APPROVED** [review]

**Review by AleksKnezevic — APPROVED** [review]
