### PR TITLE
Fix stablehlo.scatter op when scatter_dims_to_operand_dims != inserted_window_dims

### LINKED ISSUE #7667: Add stablehlo.scatter op
Currently when running af3 we get the following stablehlo.scatter op:
```
%58815 = "stablehlo.scatter"(%58751, %58814, %58803) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<update_window_dims = [0, 1, 2, 3], scatter_dims_to_operand_dims = [1, 2, 3]>, unique_indices = true}> ({
    ^bb0(%arg435: tensor<bf16> loc(callsite(#loc709 at #loc13482)), %arg436: tensor<bf16> loc(callsite(#loc709 at #loc13482))):
      stablehlo.return %arg436 : tensor<bf16> loc(#loc14149)
    }) : (tensor<1x256x256x128xbf16>, tensor<3xi32>, tensor<1x128x256x128xbf16>) -> tensor<1x256x256x128xbf16> loc(#loc14149)
```
Since the ```scatter_dims_to_operand_dims != inserted_window_dims``` this op fails with:
```
failed to legalize operation 'stablehlo.scatter'
```

### PR DESCRIPTION
**Pull request by aorlovicTT**
### Ticket
Closes #7667 

### Problem description
In the issue.

### What's changed
Added support to ```stablehlo.scatter``` when ```scatter_dims_to_operand_dims != inserted_window_dims```
APInt is used to construct DenseIntElementsAttr for  
  window offset constants, matching the bit width of the scatter index type

### Checklist
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 1]
```diff
@@ -5351,38 +5165,57 @@ class StableHLOToTTIRScatterOpConversionPattern
...
-        indexSlices.push_back(sliced);
-        ++origIdxPos;
-      } else {
-        // This dimension is a window dimension - use window offset.
-        indexSlices.push_back(windowOffsetSlices[windowIdxPos]);
+      if (isWindowDim) {
+        Value windowOffset = windowOffsetSlices[windowIdxPos];
         ++windowIdxPos;
+
+        if (dimIndex) {
```
Comment (acicovicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp]: I think it makes more sense to use `if (isScatterDim)` here, because `isScatterDim` and `isWindowDim` are now the flags that control the flow between the three possible code paths. As far as I can see, `dimIndex` is always set when `isScatterDim` is `true`.

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 2]
```diff
@@ -5351,38 +5165,57 @@ class StableHLOToTTIRScatterOpConversionPattern
       windowOffsetSlices.push_back(finalOffset);
     }
 
-    // Build per-dimension index slices by interleaving original indices
-    // and window offsets according to operand dimension order.
+    // Build per-dimension index slices. Each operand dimension can be:
+    // inserted (collapsed) + scatter-indexed: use scatter index only
```
Comment (acicovicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp]: I suggest explicitly enumerating these three code paths a), b), and c), and point them out in the comments later under the appropriate `isScatterDim`/`isWindowDim` branches to improve code readability

File: lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp [hunk 3]
```diff
@@ -5328,11 +5140,13 @@ class StableHLOToTTIRScatterOpConversionPattern
       // position. Pattern: [w0, w1, ..., wN-1, w0, w1, ..., wN-1, ...]
       //                     |---- window ---|  |--- window ----|
       //                    |--------- numScatterPositions times -----|
-      llvm::SmallVector<int64_t> finalOffsetValues;
+      unsigned bitWidth = indexElementType.getIntOrFloatBitWidth();
+
+      llvm::SmallVector<APInt> finalOffsetValues;
```
Comment (acicovicTT) [inline lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp:6026]: Please point out the APInt change in PR description, since it's an unrelated improvement to support i32 indices
