### PR TITLE
Add output verifier shape for reduction ops and fix erroneous tests

### LINKED ISSUE #1942: ttnn::mean failing thru TTRT but not in EmitC
For some reason, a simple ttnn::mean test is failing thru TTRT but not thru EmitC path.

Test:
```mlir
// RUN: ttmlir-opt --ttir-to-ttnn-backend-pipeline="system-desc-path=%system_desc_path%" %s > %t.mlir
// RUN: ttmlir-translate --ttnn-to-flatbuffer %t.mlir > %t.ttnn

func.func @forward(%arg0: tensor<512x1024xbf16>) -> tensor<512x32xbf16> {
  %0 = tensor.empty() : tensor<512x32xbf16>
  %1 = "ttir.mean"(%arg0, %0) <{dim_arg = [-1: i32], keep_dim = true}> : (tensor<512x1024xbf16>, tensor<512x32xbf16>) -> tensor<512x32xbf16>
  return %1 : tensor<512x32xbf16>
}
```

Repro:
```
git checkout svuckovic/repro-1942
# build...
llvm-lit -sv test/ttmlir/Silicon/TTNN/repro_mean.mlir
ttrt run build/test/ttmlir/Silicon/TTNN/Output/repro_mean.mlir.tmp.ttnn
```

My assumption is it has to do with the added memory config in `runtime/lib/ttnn/operations/reduction/reduction.cpp::runReductionOp`.

### PR DESCRIPTION
**Pull request by svuckovicTT**
- Added verifier for reduction ops - tests whether output shape matches what the op will return.
- Fixed tests so that IRs are correct

Closes #1942

### CODE REVIEW

**Comment by svuckovicTT** [comment]
fyi @mrakitaTT

File: lib/Dialect/TTNN/IR/TTNNOps.cpp [hunk 1]
```diff
@@ -1566,6 +1571,45 @@ verifyReduceOp(mlir::Operation *reduceOp, mlir::RankedTensorType inputType,
                                  "currently supported by TTNN");
   }
 
+  // Calculate output shape for given args.
+  //
+  llvm::SmallVector<int64_t, 4> calculatedOutputShape;
```
Comment (azecevicTT) [inline lib/Dialect/TTNN/IR/TTNNOps.cpp:1576]: `, 4>` part is not needed.

File: lib/Dialect/TTNN/IR/TTNNOps.cpp [hunk 2]
```diff
@@ -1566,6 +1571,45 @@ verifyReduceOp(mlir::Operation *reduceOp, mlir::RankedTensorType inputType,
...
+          //
+          return reduceDim == i || (reduceDim + inputTensorRank) == i;
+        });
+
+    // If dim is being reduced on, the dim will have size of 1 if keepDim==true,
+    // otherwise the dim is erased.
+    //
+    if (!isDimInReduceDims) {
+      calculatedOutputShape.push_back(inputType.getDimSize(i));
+      continue;
```
Comment (azecevicTT) [inline lib/Dialect/TTNN/IR/TTNNOps.cpp:1591]: `continue` is overused here, you can still have one level of nesting without it.
```cpp
if (!isDimInReduceDims) {
  ...
} else if (keepDim) {
  ...
}
```

**Review by azecevicTT — APPROVED** [review]

**Comment by sdjordjevicTT** [comment]
I belive this PR closes this issue as well:
https://github.com/tenstorrent/tt-mlir/issues/1639

**Review by sdjordjevicTT — APPROVED** [review]

**Comment by mrakitaTT** [comment]
@svuckovicTT Seeing this late, thank you for figuring this out and expanding the verifier! 🙏
