### PR TITLE
Fix LinearOp parameter order to match MatmulOp

### LINKED ISSUE #6552: LinearOp has inconsistent parameter order for activation and matmul_program_config
## Description

In the TableGen definitions for `TTNN_LinearOp` and `TTNN_MatmulOp`, the parameter order for `activation` and `matmul_program_config` is inconsistent.

**LinearOp** (incorrect order):
- `activation` (line 1489)
- `matmul_program_config` (lines 1490-1495)

**MatmulOp** (correct order):
- `matmul_program_config` (lines 1520-1525)
- `activation` (line 1526)

The TTNN API for both `::ttnn::matmul` and `::ttnn::linear` expects `programConfig` before `activation`, which matches MatmulOp's order. LinearOp should be updated to match this convention.

### PR DESCRIPTION
**Pull request by rpavlovicTT**
LinearOp had matmul_program_config after activation in the TableGen definition, which was inconsistent with MatmulOp (which has matmul_program_config before activation) and the TTNN API.

Fixes #6552

### CODE REVIEW

File: lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp [hunk 1]
```diff
@@ -1143,8 +1143,8 @@ class LinearOpConversionPattern : public OpConversionPattern<ttir::LinearOp> {
     rewriter.replaceOpWithNewOp<ttnn::LinearOp>(
         op, this->getTypeConverter()->convertType(op.getType()), adaptor.getA(),
         adaptor.getB(), adaptor.getBias(), adaptor.getTransposeA(),
-        adaptor.getTransposeB(), /*activation=*/nullptr,
-        /*matmul_program_config=*/nullptr, /*compute_config=*/nullptr);
+        adaptor.getTransposeB(), /*matmul_program_config=*/nullptr,
+        /*activation=*/nullptr, /*compute_config=*/nullptr);
```
Comment (svuckovicTT) [inline lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp:1147]: Can you fix emitpy/c as well please? Thanks!

Comment (rpavlovicTT) [reply lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp:1147]: Yes I will merge this first, and then rebase https://github.com/tenstorrent/tt-mlir/pull/6462 and fix it there.
